export { default as AdminCreateMarkList } from './AdminCreateMarkList';
export { default as AdminDashboard } from './AdminDashboard';
export { default as AdminEnrollUser } from './AdminEnrollUser';
export { default as AdminManageEvent } from './AdminManageEvent.jsx';
export { default as AdminManageStudents } from './AdminManageStud';
export { default as AdminManageTeacher } from './AdminManageTeach';
export { default as AdminUpdateProfile } from './AdminUpdateProfile';
export { default as AdminUserAccessControl } from './AdminUserAccessControl';
export { default as AdminEventForm } from './AdminEventForm';
