#!/bin/bash
set -e

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<-EOSQL
  DROP DATABASE IF EXISTS ${DEV_MYSQL_DB};
  DROP DATABASE IF EXISTS ${TEST_MYSQL_DB};

  DROP USER IF EXISTS '${DEV_MYSQL_USER}'@'%';
  DROP USER IF EXISTS '${TEST_MYSQL_USER}'@'%';

  CREATE DATABASE IF NOT EXISTS ${DEV_MYSQL_DB};
  CREATE DATABASE IF NOT EXISTS ${TEST_MYSQL_DB};

  CREATE USER IF NOT EXISTS '${DEV_MYSQL_USER}'@'%' IDENTIFIED BY '${DEV_MYSQL_PWD}';
  CREATE USER IF NOT EXISTS '${TEST_MYSQL_USER}'@'%' IDENTIFIED BY '${TEST_MYSQL_PWD}';

  GRANT ALL PRIVILEGES ON ${DEV_MYSQL_DB}.* TO '${DEV_MYSQL_USER}'@'%';
  GRANT ALL PRIVILEGES ON ${TEST_MYSQL_DB}.* TO '${TEST_MYSQL_USER}'@'%';

  GRANT SELECT ON performance_schema.* TO '${DEV_MYSQL_USER}'@'%';
  GRANT SELECT ON performance_schema.* TO '${TEST_MYSQL_USER}'@'%';

  FLUSH PRIVILEGES;
EOSQL
