version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  devcontiner:
    # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer 
    # folder. Note that the path of the Dockerfile and context is relative to the *primary* 
    # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
    # array). The sample below assumes your primary file is in the root of your project.
    container_name: classease_devcontainer
    depends_on:
      - db  # Ensures MySQL starts first
    networks:
      - app-network
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    privileged: true  # Required for Docker-in-Docker
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock  # Optional (alternative to DinD)
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
 
networks:
  app-network:
    external: true
