/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminYearIndexRouteImport } from './routes/admin/year/index'
import { Route as AdminSubjectsIndexRouteImport } from './routes/admin/subjects/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminGradesIndexRouteImport } from './routes/admin/grades/index'
import { Route as AdminRegistrationTeacherRouteImport } from './routes/admin/registration/teacher'
import { Route as AdminRegistrationStudentRouteImport } from './routes/admin/registration/student'
import { Route as AdminRegistrationNewTeacherRouteImport } from './routes/admin/registration/new-teacher'
import { Route as AdminRegistrationNewStudentRouteImport } from './routes/admin/registration/new-student'
import { Route as AdminYearYearIdIndexRouteImport } from './routes/admin/year/$yearId/index'
import { Route as AdminSubjectsSubjectIdIndexRouteImport } from './routes/admin/subjects/$subjectId/index'
import { Route as AdminStudentsStudentIdIndexRouteImport } from './routes/admin/students/$studentId/index'
import { Route as AdminGradesGradeIdIndexRouteImport } from './routes/admin/grades/$gradeId/index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/authentication/',
  path: '/authentication/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminYearIndexRoute = AdminYearIndexRouteImport.update({
  id: '/year/',
  path: '/year/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubjectsIndexRoute = AdminSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGradesIndexRoute = AdminGradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegistrationTeacherRoute =
  AdminRegistrationTeacherRouteImport.update({
    id: '/registration/teacher',
    path: '/registration/teacher',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRegistrationStudentRoute =
  AdminRegistrationStudentRouteImport.update({
    id: '/registration/student',
    path: '/registration/student',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRegistrationNewTeacherRoute =
  AdminRegistrationNewTeacherRouteImport.update({
    id: '/registration/new-teacher',
    path: '/registration/new-teacher',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRegistrationNewStudentRoute =
  AdminRegistrationNewStudentRouteImport.update({
    id: '/registration/new-student',
    path: '/registration/new-student',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminYearYearIdIndexRoute = AdminYearYearIdIndexRouteImport.update({
  id: '/year/$yearId/',
  path: '/year/$yearId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubjectsSubjectIdIndexRoute =
  AdminSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminStudentsStudentIdIndexRoute =
  AdminStudentsStudentIdIndexRouteImport.update({
    id: '/students/$studentId/',
    path: '/students/$studentId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminGradesGradeIdIndexRoute = AdminGradesGradeIdIndexRouteImport.update({
  id: '/grades/$gradeId/',
  path: '/grades/$gradeId/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/registration/new-student': typeof AdminRegistrationNewStudentRoute
  '/admin/registration/new-teacher': typeof AdminRegistrationNewTeacherRoute
  '/admin/registration/student': typeof AdminRegistrationStudentRoute
  '/admin/registration/teacher': typeof AdminRegistrationTeacherRoute
  '/admin/grades': typeof AdminGradesIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/subjects': typeof AdminSubjectsIndexRoute
  '/admin/year': typeof AdminYearIndexRoute
  '/admin/grades/$gradeId': typeof AdminGradesGradeIdIndexRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdIndexRoute
  '/admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdIndexRoute
  '/admin/year/$yearId': typeof AdminYearYearIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/registration/new-student': typeof AdminRegistrationNewStudentRoute
  '/admin/registration/new-teacher': typeof AdminRegistrationNewTeacherRoute
  '/admin/registration/student': typeof AdminRegistrationStudentRoute
  '/admin/registration/teacher': typeof AdminRegistrationTeacherRoute
  '/admin/grades': typeof AdminGradesIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/subjects': typeof AdminSubjectsIndexRoute
  '/admin/year': typeof AdminYearIndexRoute
  '/admin/grades/$gradeId': typeof AdminGradesGradeIdIndexRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdIndexRoute
  '/admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdIndexRoute
  '/admin/year/$yearId': typeof AdminYearYearIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/registration/new-student': typeof AdminRegistrationNewStudentRoute
  '/admin/registration/new-teacher': typeof AdminRegistrationNewTeacherRoute
  '/admin/registration/student': typeof AdminRegistrationStudentRoute
  '/admin/registration/teacher': typeof AdminRegistrationTeacherRoute
  '/admin/grades/': typeof AdminGradesIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/subjects/': typeof AdminSubjectsIndexRoute
  '/admin/year/': typeof AdminYearIndexRoute
  '/admin/grades/$gradeId/': typeof AdminGradesGradeIdIndexRoute
  '/admin/students/$studentId/': typeof AdminStudentsStudentIdIndexRoute
  '/admin/subjects/$subjectId/': typeof AdminSubjectsSubjectIdIndexRoute
  '/admin/year/$yearId/': typeof AdminYearYearIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/authentication'
    | '/student'
    | '/teacher'
    | '/admin/registration/new-student'
    | '/admin/registration/new-teacher'
    | '/admin/registration/student'
    | '/admin/registration/teacher'
    | '/admin/grades'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/year'
    | '/admin/grades/$gradeId'
    | '/admin/students/$studentId'
    | '/admin/subjects/$subjectId'
    | '/admin/year/$yearId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/authentication'
    | '/student'
    | '/teacher'
    | '/admin/registration/new-student'
    | '/admin/registration/new-teacher'
    | '/admin/registration/student'
    | '/admin/registration/teacher'
    | '/admin/grades'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/year'
    | '/admin/grades/$gradeId'
    | '/admin/students/$studentId'
    | '/admin/subjects/$subjectId'
    | '/admin/year/$yearId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/'
    | '/authentication/'
    | '/student/'
    | '/teacher/'
    | '/admin/registration/new-student'
    | '/admin/registration/new-teacher'
    | '/admin/registration/student'
    | '/admin/registration/teacher'
    | '/admin/grades/'
    | '/admin/students/'
    | '/admin/subjects/'
    | '/admin/year/'
    | '/admin/grades/$gradeId/'
    | '/admin/students/$studentId/'
    | '/admin/subjects/$subjectId/'
    | '/admin/year/$yearId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/year/': {
      id: '/admin/year/'
      path: '/year'
      fullPath: '/admin/year'
      preLoaderRoute: typeof AdminYearIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subjects/': {
      id: '/admin/subjects/'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/grades/': {
      id: '/admin/grades/'
      path: '/grades'
      fullPath: '/admin/grades'
      preLoaderRoute: typeof AdminGradesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration/teacher': {
      id: '/admin/registration/teacher'
      path: '/registration/teacher'
      fullPath: '/admin/registration/teacher'
      preLoaderRoute: typeof AdminRegistrationTeacherRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration/student': {
      id: '/admin/registration/student'
      path: '/registration/student'
      fullPath: '/admin/registration/student'
      preLoaderRoute: typeof AdminRegistrationStudentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration/new-teacher': {
      id: '/admin/registration/new-teacher'
      path: '/registration/new-teacher'
      fullPath: '/admin/registration/new-teacher'
      preLoaderRoute: typeof AdminRegistrationNewTeacherRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration/new-student': {
      id: '/admin/registration/new-student'
      path: '/registration/new-student'
      fullPath: '/admin/registration/new-student'
      preLoaderRoute: typeof AdminRegistrationNewStudentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/year/$yearId/': {
      id: '/admin/year/$yearId/'
      path: '/year/$yearId'
      fullPath: '/admin/year/$yearId'
      preLoaderRoute: typeof AdminYearYearIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subjects/$subjectId/': {
      id: '/admin/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/admin/subjects/$subjectId'
      preLoaderRoute: typeof AdminSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/$studentId/': {
      id: '/admin/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/grades/$gradeId/': {
      id: '/admin/grades/$gradeId/'
      path: '/grades/$gradeId'
      fullPath: '/admin/grades/$gradeId'
      preLoaderRoute: typeof AdminGradesGradeIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRegistrationNewStudentRoute: typeof AdminRegistrationNewStudentRoute
  AdminRegistrationNewTeacherRoute: typeof AdminRegistrationNewTeacherRoute
  AdminRegistrationStudentRoute: typeof AdminRegistrationStudentRoute
  AdminRegistrationTeacherRoute: typeof AdminRegistrationTeacherRoute
  AdminGradesIndexRoute: typeof AdminGradesIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminSubjectsIndexRoute: typeof AdminSubjectsIndexRoute
  AdminYearIndexRoute: typeof AdminYearIndexRoute
  AdminGradesGradeIdIndexRoute: typeof AdminGradesGradeIdIndexRoute
  AdminStudentsStudentIdIndexRoute: typeof AdminStudentsStudentIdIndexRoute
  AdminSubjectsSubjectIdIndexRoute: typeof AdminSubjectsSubjectIdIndexRoute
  AdminYearYearIdIndexRoute: typeof AdminYearYearIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminRegistrationNewStudentRoute: AdminRegistrationNewStudentRoute,
  AdminRegistrationNewTeacherRoute: AdminRegistrationNewTeacherRoute,
  AdminRegistrationStudentRoute: AdminRegistrationStudentRoute,
  AdminRegistrationTeacherRoute: AdminRegistrationTeacherRoute,
  AdminGradesIndexRoute: AdminGradesIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminSubjectsIndexRoute: AdminSubjectsIndexRoute,
  AdminYearIndexRoute: AdminYearIndexRoute,
  AdminGradesGradeIdIndexRoute: AdminGradesGradeIdIndexRoute,
  AdminStudentsStudentIdIndexRoute: AdminStudentsStudentIdIndexRoute,
  AdminSubjectsSubjectIdIndexRoute: AdminSubjectsSubjectIdIndexRoute,
  AdminYearYearIdIndexRoute: AdminYearYearIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
