/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as AuthenticationIndexRouteImport } from './routes/authentication/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminYearIndexRouteImport } from './routes/admin/year/index'
import { Route as AdminSubjectsIndexRouteImport } from './routes/admin/subjects/index'
import { Route as AdminStudentsIndexRouteImport } from './routes/admin/students/index'
import { Route as AdminManageTeachersIndexRouteImport } from './routes/admin/manage-teachers/index'
import { Route as AdminGradesIndexRouteImport } from './routes/admin/grades/index'
import { Route as AdminEmployeesIndexRouteImport } from './routes/admin/employees/index'
import { Route as AdminRegistrationStudentsRouteImport } from './routes/admin/registration/students'
import { Route as AdminRegistrationNewStudentRouteImport } from './routes/admin/registration/new-student'
import { Route as AdminRegistrationNewEmployeeRouteImport } from './routes/admin/registration/new-employee'
import { Route as AdminRegistrationEmployeesRouteImport } from './routes/admin/registration/employees'
import { Route as AdminEmployeesEmployeeIdRouteRouteImport } from './routes/admin/employees/$employeeId/route'
import { Route as AdminYearYearIdIndexRouteImport } from './routes/admin/year/$yearId/index'
import { Route as AdminSubjectsSubjectIdIndexRouteImport } from './routes/admin/subjects/$subjectId/index'
import { Route as AdminStudentsStudentIdIndexRouteImport } from './routes/admin/students/$studentId/index'
import { Route as AdminGradesGradeIdIndexRouteImport } from './routes/admin/grades/$gradeId/index'
import { Route as AdminEmployeesEmployeeIdProfileIndexRouteImport } from './routes/admin/employees/$employeeId/profile/index'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationIndexRoute = AuthenticationIndexRouteImport.update({
  id: '/authentication/',
  path: '/authentication/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminYearIndexRoute = AdminYearIndexRouteImport.update({
  id: '/year/',
  path: '/year/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubjectsIndexRoute = AdminSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStudentsIndexRoute = AdminStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminManageTeachersIndexRoute =
  AdminManageTeachersIndexRouteImport.update({
    id: '/manage-teachers/',
    path: '/manage-teachers/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminGradesIndexRoute = AdminGradesIndexRouteImport.update({
  id: '/grades/',
  path: '/grades/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesIndexRoute = AdminEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRegistrationStudentsRoute =
  AdminRegistrationStudentsRouteImport.update({
    id: '/registration/students',
    path: '/registration/students',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRegistrationNewStudentRoute =
  AdminRegistrationNewStudentRouteImport.update({
    id: '/registration/new-student',
    path: '/registration/new-student',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRegistrationNewEmployeeRoute =
  AdminRegistrationNewEmployeeRouteImport.update({
    id: '/registration/new-employee',
    path: '/registration/new-employee',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminRegistrationEmployeesRoute =
  AdminRegistrationEmployeesRouteImport.update({
    id: '/registration/employees',
    path: '/registration/employees',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminEmployeesEmployeeIdRouteRoute =
  AdminEmployeesEmployeeIdRouteRouteImport.update({
    id: '/employees/$employeeId',
    path: '/employees/$employeeId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminYearYearIdIndexRoute = AdminYearYearIdIndexRouteImport.update({
  id: '/year/$yearId/',
  path: '/year/$yearId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubjectsSubjectIdIndexRoute =
  AdminSubjectsSubjectIdIndexRouteImport.update({
    id: '/subjects/$subjectId/',
    path: '/subjects/$subjectId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminStudentsStudentIdIndexRoute =
  AdminStudentsStudentIdIndexRouteImport.update({
    id: '/students/$studentId/',
    path: '/students/$studentId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminGradesGradeIdIndexRoute = AdminGradesGradeIdIndexRouteImport.update({
  id: '/grades/$gradeId/',
  path: '/grades/$gradeId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesEmployeeIdProfileIndexRoute =
  AdminEmployeesEmployeeIdProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AdminEmployeesEmployeeIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRouteRouteWithChildren
  '/admin/registration/employees': typeof AdminRegistrationEmployeesRoute
  '/admin/registration/new-employee': typeof AdminRegistrationNewEmployeeRoute
  '/admin/registration/new-student': typeof AdminRegistrationNewStudentRoute
  '/admin/registration/students': typeof AdminRegistrationStudentsRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/grades': typeof AdminGradesIndexRoute
  '/admin/manage-teachers': typeof AdminManageTeachersIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/subjects': typeof AdminSubjectsIndexRoute
  '/admin/year': typeof AdminYearIndexRoute
  '/admin/grades/$gradeId': typeof AdminGradesGradeIdIndexRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdIndexRoute
  '/admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdIndexRoute
  '/admin/year/$yearId': typeof AdminYearYearIdIndexRoute
  '/admin/employees/$employeeId/profile': typeof AdminEmployeesEmployeeIdProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/authentication': typeof AuthenticationIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRouteRouteWithChildren
  '/admin/registration/employees': typeof AdminRegistrationEmployeesRoute
  '/admin/registration/new-employee': typeof AdminRegistrationNewEmployeeRoute
  '/admin/registration/new-student': typeof AdminRegistrationNewStudentRoute
  '/admin/registration/students': typeof AdminRegistrationStudentsRoute
  '/admin/employees': typeof AdminEmployeesIndexRoute
  '/admin/grades': typeof AdminGradesIndexRoute
  '/admin/manage-teachers': typeof AdminManageTeachersIndexRoute
  '/admin/students': typeof AdminStudentsIndexRoute
  '/admin/subjects': typeof AdminSubjectsIndexRoute
  '/admin/year': typeof AdminYearIndexRoute
  '/admin/grades/$gradeId': typeof AdminGradesGradeIdIndexRoute
  '/admin/students/$studentId': typeof AdminStudentsStudentIdIndexRoute
  '/admin/subjects/$subjectId': typeof AdminSubjectsSubjectIdIndexRoute
  '/admin/year/$yearId': typeof AdminYearYearIdIndexRoute
  '/admin/employees/$employeeId/profile': typeof AdminEmployeesEmployeeIdProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/authentication/': typeof AuthenticationIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/employees/$employeeId': typeof AdminEmployeesEmployeeIdRouteRouteWithChildren
  '/admin/registration/employees': typeof AdminRegistrationEmployeesRoute
  '/admin/registration/new-employee': typeof AdminRegistrationNewEmployeeRoute
  '/admin/registration/new-student': typeof AdminRegistrationNewStudentRoute
  '/admin/registration/students': typeof AdminRegistrationStudentsRoute
  '/admin/employees/': typeof AdminEmployeesIndexRoute
  '/admin/grades/': typeof AdminGradesIndexRoute
  '/admin/manage-teachers/': typeof AdminManageTeachersIndexRoute
  '/admin/students/': typeof AdminStudentsIndexRoute
  '/admin/subjects/': typeof AdminSubjectsIndexRoute
  '/admin/year/': typeof AdminYearIndexRoute
  '/admin/grades/$gradeId/': typeof AdminGradesGradeIdIndexRoute
  '/admin/students/$studentId/': typeof AdminStudentsStudentIdIndexRoute
  '/admin/subjects/$subjectId/': typeof AdminSubjectsSubjectIdIndexRoute
  '/admin/year/$yearId/': typeof AdminYearYearIdIndexRoute
  '/admin/employees/$employeeId/profile/': typeof AdminEmployeesEmployeeIdProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/'
    | '/authentication'
    | '/student'
    | '/admin/employees/$employeeId'
    | '/admin/registration/employees'
    | '/admin/registration/new-employee'
    | '/admin/registration/new-student'
    | '/admin/registration/students'
    | '/admin/employees'
    | '/admin/grades'
    | '/admin/manage-teachers'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/year'
    | '/admin/grades/$gradeId'
    | '/admin/students/$studentId'
    | '/admin/subjects/$subjectId'
    | '/admin/year/$yearId'
    | '/admin/employees/$employeeId/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/authentication'
    | '/student'
    | '/admin/employees/$employeeId'
    | '/admin/registration/employees'
    | '/admin/registration/new-employee'
    | '/admin/registration/new-student'
    | '/admin/registration/students'
    | '/admin/employees'
    | '/admin/grades'
    | '/admin/manage-teachers'
    | '/admin/students'
    | '/admin/subjects'
    | '/admin/year'
    | '/admin/grades/$gradeId'
    | '/admin/students/$studentId'
    | '/admin/subjects/$subjectId'
    | '/admin/year/$yearId'
    | '/admin/employees/$employeeId/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/'
    | '/authentication/'
    | '/student/'
    | '/admin/employees/$employeeId'
    | '/admin/registration/employees'
    | '/admin/registration/new-employee'
    | '/admin/registration/new-student'
    | '/admin/registration/students'
    | '/admin/employees/'
    | '/admin/grades/'
    | '/admin/manage-teachers/'
    | '/admin/students/'
    | '/admin/subjects/'
    | '/admin/year/'
    | '/admin/grades/$gradeId/'
    | '/admin/students/$studentId/'
    | '/admin/subjects/$subjectId/'
    | '/admin/year/$yearId/'
    | '/admin/employees/$employeeId/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticationIndexRoute: typeof AuthenticationIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication/': {
      id: '/authentication/'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/year/': {
      id: '/admin/year/'
      path: '/year'
      fullPath: '/admin/year'
      preLoaderRoute: typeof AdminYearIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subjects/': {
      id: '/admin/subjects/'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AdminSubjectsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/': {
      id: '/admin/students/'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/manage-teachers/': {
      id: '/admin/manage-teachers/'
      path: '/manage-teachers'
      fullPath: '/admin/manage-teachers'
      preLoaderRoute: typeof AdminManageTeachersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/grades/': {
      id: '/admin/grades/'
      path: '/grades'
      fullPath: '/admin/grades'
      preLoaderRoute: typeof AdminGradesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/': {
      id: '/admin/employees/'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration/students': {
      id: '/admin/registration/students'
      path: '/registration/students'
      fullPath: '/admin/registration/students'
      preLoaderRoute: typeof AdminRegistrationStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration/new-student': {
      id: '/admin/registration/new-student'
      path: '/registration/new-student'
      fullPath: '/admin/registration/new-student'
      preLoaderRoute: typeof AdminRegistrationNewStudentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration/new-employee': {
      id: '/admin/registration/new-employee'
      path: '/registration/new-employee'
      fullPath: '/admin/registration/new-employee'
      preLoaderRoute: typeof AdminRegistrationNewEmployeeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/registration/employees': {
      id: '/admin/registration/employees'
      path: '/registration/employees'
      fullPath: '/admin/registration/employees'
      preLoaderRoute: typeof AdminRegistrationEmployeesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/$employeeId': {
      id: '/admin/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/admin/employees/$employeeId'
      preLoaderRoute: typeof AdminEmployeesEmployeeIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/year/$yearId/': {
      id: '/admin/year/$yearId/'
      path: '/year/$yearId'
      fullPath: '/admin/year/$yearId'
      preLoaderRoute: typeof AdminYearYearIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subjects/$subjectId/': {
      id: '/admin/subjects/$subjectId/'
      path: '/subjects/$subjectId'
      fullPath: '/admin/subjects/$subjectId'
      preLoaderRoute: typeof AdminSubjectsSubjectIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/students/$studentId/': {
      id: '/admin/students/$studentId/'
      path: '/students/$studentId'
      fullPath: '/admin/students/$studentId'
      preLoaderRoute: typeof AdminStudentsStudentIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/grades/$gradeId/': {
      id: '/admin/grades/$gradeId/'
      path: '/grades/$gradeId'
      fullPath: '/admin/grades/$gradeId'
      preLoaderRoute: typeof AdminGradesGradeIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees/$employeeId/profile/': {
      id: '/admin/employees/$employeeId/profile/'
      path: '/profile'
      fullPath: '/admin/employees/$employeeId/profile'
      preLoaderRoute: typeof AdminEmployeesEmployeeIdProfileIndexRouteImport
      parentRoute: typeof AdminEmployeesEmployeeIdRouteRoute
    }
  }
}

interface AdminEmployeesEmployeeIdRouteRouteChildren {
  AdminEmployeesEmployeeIdProfileIndexRoute: typeof AdminEmployeesEmployeeIdProfileIndexRoute
}

const AdminEmployeesEmployeeIdRouteRouteChildren: AdminEmployeesEmployeeIdRouteRouteChildren =
  {
    AdminEmployeesEmployeeIdProfileIndexRoute:
      AdminEmployeesEmployeeIdProfileIndexRoute,
  }

const AdminEmployeesEmployeeIdRouteRouteWithChildren =
  AdminEmployeesEmployeeIdRouteRoute._addFileChildren(
    AdminEmployeesEmployeeIdRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmployeesEmployeeIdRouteRoute: typeof AdminEmployeesEmployeeIdRouteRouteWithChildren
  AdminRegistrationEmployeesRoute: typeof AdminRegistrationEmployeesRoute
  AdminRegistrationNewEmployeeRoute: typeof AdminRegistrationNewEmployeeRoute
  AdminRegistrationNewStudentRoute: typeof AdminRegistrationNewStudentRoute
  AdminRegistrationStudentsRoute: typeof AdminRegistrationStudentsRoute
  AdminEmployeesIndexRoute: typeof AdminEmployeesIndexRoute
  AdminGradesIndexRoute: typeof AdminGradesIndexRoute
  AdminManageTeachersIndexRoute: typeof AdminManageTeachersIndexRoute
  AdminStudentsIndexRoute: typeof AdminStudentsIndexRoute
  AdminSubjectsIndexRoute: typeof AdminSubjectsIndexRoute
  AdminYearIndexRoute: typeof AdminYearIndexRoute
  AdminGradesGradeIdIndexRoute: typeof AdminGradesGradeIdIndexRoute
  AdminStudentsStudentIdIndexRoute: typeof AdminStudentsStudentIdIndexRoute
  AdminSubjectsSubjectIdIndexRoute: typeof AdminSubjectsSubjectIdIndexRoute
  AdminYearYearIdIndexRoute: typeof AdminYearYearIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminEmployeesEmployeeIdRouteRoute:
    AdminEmployeesEmployeeIdRouteRouteWithChildren,
  AdminRegistrationEmployeesRoute: AdminRegistrationEmployeesRoute,
  AdminRegistrationNewEmployeeRoute: AdminRegistrationNewEmployeeRoute,
  AdminRegistrationNewStudentRoute: AdminRegistrationNewStudentRoute,
  AdminRegistrationStudentsRoute: AdminRegistrationStudentsRoute,
  AdminEmployeesIndexRoute: AdminEmployeesIndexRoute,
  AdminGradesIndexRoute: AdminGradesIndexRoute,
  AdminManageTeachersIndexRoute: AdminManageTeachersIndexRoute,
  AdminStudentsIndexRoute: AdminStudentsIndexRoute,
  AdminSubjectsIndexRoute: AdminSubjectsIndexRoute,
  AdminYearIndexRoute: AdminYearIndexRoute,
  AdminGradesGradeIdIndexRoute: AdminGradesGradeIdIndexRoute,
  AdminStudentsStudentIdIndexRoute: AdminStudentsStudentIdIndexRoute,
  AdminSubjectsSubjectIdIndexRoute: AdminSubjectsSubjectIdIndexRoute,
  AdminYearYearIdIndexRoute: AdminYearYearIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticationIndexRoute: AuthenticationIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
