// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options,
  login,
  logout,
  registerNewAdmin,
  registerStudentStep1,
  registerStudentStep2,
  registerStudentStep3,
  registerStudentStep4,
  registerStudentStep5,
  registerNewStudent,
  registerEmployeeStep1,
  registerEmployeeStep2,
  registerEmployeeStep3,
  registerEmployeeStep4,
  registerEmployeeStep5,
  registerNewEmployee,
  getYears,
  postYear,
  getYearSummary,
  deleteYear,
  getYearById,
  getDetailGradesByYearId,
  getDetailSubjectsByYearId,
  getGrades,
  postGrade,
  getGradesSetup,
  getGradesSetupById,
  patchGradeSetup,
  getGradeById,
  getSubjects,
  postSubject,
  getSubjectsSetup,
  getSubjectSetupById,
  patchSubjectSetup,
  getSubjectById,
  getStreams,
  getStreamById,
  getSections,
  getSectionById,
  getLoggedInUser,
  getAdminBasicInfo,
  getTeacherBasicInfo,
  getStudentBasicInfo,
  deleteStudents,
  getStudents,
  getStudent,
  updateStudentStatus,
  deleteEmployees,
  getEmployees,
  getEmployee,
  updateEmployeeStatus,
  getTeachers,
  assignTeacher,
} from "../sdk.gen";
import {
  queryOptions,
  type UseMutationOptions,
  type DefaultError,
} from "@tanstack/react-query";
import type {
  LoginData,
  LoginError,
  LoginResponse,
  LogoutData,
  LogoutResponse,
  RegisterNewAdminData,
  RegisterNewAdminError,
  RegisterNewAdminResponse,
  RegisterStudentStep1Data,
  RegisterStudentStep1Error,
  RegisterStudentStep1Response,
  RegisterStudentStep2Data,
  RegisterStudentStep2Error,
  RegisterStudentStep2Response,
  RegisterStudentStep3Data,
  RegisterStudentStep3Error,
  RegisterStudentStep3Response,
  RegisterStudentStep4Data,
  RegisterStudentStep4Error,
  RegisterStudentStep4Response,
  RegisterStudentStep5Data,
  RegisterStudentStep5Error,
  RegisterStudentStep5Response,
  RegisterNewStudentData,
  RegisterNewStudentError,
  RegisterNewStudentResponse,
  RegisterEmployeeStep1Data,
  RegisterEmployeeStep1Error,
  RegisterEmployeeStep1Response,
  RegisterEmployeeStep2Data,
  RegisterEmployeeStep2Error,
  RegisterEmployeeStep2Response,
  RegisterEmployeeStep3Data,
  RegisterEmployeeStep3Error,
  RegisterEmployeeStep3Response,
  RegisterEmployeeStep4Data,
  RegisterEmployeeStep4Error,
  RegisterEmployeeStep4Response,
  RegisterEmployeeStep5Data,
  RegisterEmployeeStep5Error,
  RegisterEmployeeStep5Response,
  RegisterNewEmployeeData,
  RegisterNewEmployeeError,
  RegisterNewEmployeeResponse,
  GetYearsData,
  PostYearData,
  PostYearError,
  PostYearResponse,
  GetYearSummaryData,
  DeleteYearData,
  DeleteYearError,
  DeleteYearResponse,
  GetYearByIdData,
  GetDetailGradesByYearIdData,
  GetDetailSubjectsByYearIdData,
  GetGradesData,
  PostGradeData,
  PostGradeError,
  PostGradeResponse,
  GetGradesSetupData,
  GetGradesSetupByIdData,
  PatchGradeSetupData,
  PatchGradeSetupError,
  PatchGradeSetupResponse,
  GetGradeByIdData,
  GetSubjectsData,
  PostSubjectData,
  PostSubjectError,
  PostSubjectResponse,
  GetSubjectsSetupData,
  GetSubjectSetupByIdData,
  PatchSubjectSetupData,
  PatchSubjectSetupError,
  PatchSubjectSetupResponse,
  GetSubjectByIdData,
  GetStreamsData,
  GetStreamByIdData,
  GetSectionsData,
  GetSectionByIdData,
  GetLoggedInUserData,
  GetAdminBasicInfoData,
  GetTeacherBasicInfoData,
  GetStudentBasicInfoData,
  DeleteStudentsData,
  DeleteStudentsError,
  DeleteStudentsResponse,
  GetStudentsData,
  GetStudentData,
  UpdateStudentStatusData,
  UpdateStudentStatusError,
  UpdateStudentStatusResponse,
  DeleteEmployeesData,
  DeleteEmployeesError,
  DeleteEmployeesResponse,
  GetEmployeesData,
  GetEmployeeData,
  UpdateEmployeeStatusData,
  UpdateEmployeeStatusError,
  UpdateEmployeeStatusResponse,
  GetTeachersData,
  AssignTeacherData,
  AssignTeacherError,
  AssignTeacherResponse,
} from "../types.gen";
import type { AxiosError } from "axios";
import { client as _heyApiClient } from "../client.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseURL" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseURL:
      options?.baseURL ||
      (options?.client ?? _heyApiClient).getConfig().baseURL,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const loginQueryKey = (options: Options<LoginData>) =>
  createQueryKey("login", options);

/**
 * Login
 */
export const loginOptions = (options: Options<LoginData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await login({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: loginQueryKey(options),
  });
};

/**
 * Login
 */
export const loginMutation = (
  options?: Partial<Options<LoginData>>,
): UseMutationOptions<
  LoginResponse,
  AxiosError<LoginError>,
  Options<LoginData>
> => {
  const mutationOptions: UseMutationOptions<
    LoginResponse,
    AxiosError<LoginError>,
    Options<LoginData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await login({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const logoutQueryKey = (options?: Options<LogoutData>) =>
  createQueryKey("logout", options);

/**
 * Logout
 */
export const logoutOptions = (options?: Options<LogoutData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await logout({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: logoutQueryKey(options),
  });
};

/**
 * Logout
 */
export const logoutMutation = (
  options?: Partial<Options<LogoutData>>,
): UseMutationOptions<
  LogoutResponse,
  AxiosError<DefaultError>,
  Options<LogoutData>
> => {
  const mutationOptions: UseMutationOptions<
    LogoutResponse,
    AxiosError<DefaultError>,
    Options<LogoutData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await logout({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerNewAdminQueryKey = (
  options: Options<RegisterNewAdminData>,
) => createQueryKey("registerNewAdmin", options);

/**
 * Register New Admin
 * Registers a new admin in the system.
 */
export const registerNewAdminOptions = (
  options: Options<RegisterNewAdminData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerNewAdmin({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerNewAdminQueryKey(options),
  });
};

/**
 * Register New Admin
 * Registers a new admin in the system.
 */
export const registerNewAdminMutation = (
  options?: Partial<Options<RegisterNewAdminData>>,
): UseMutationOptions<
  RegisterNewAdminResponse,
  AxiosError<RegisterNewAdminError>,
  Options<RegisterNewAdminData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterNewAdminResponse,
    AxiosError<RegisterNewAdminError>,
    Options<RegisterNewAdminData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerNewAdmin({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerStudentStep1QueryKey = (
  options: Options<RegisterStudentStep1Data>,
) => createQueryKey("registerStudentStep1", options);

/**
 * Register Student Step1
 * Validate student data for each step
 */
export const registerStudentStep1Options = (
  options: Options<RegisterStudentStep1Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerStudentStep1({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerStudentStep1QueryKey(options),
  });
};

/**
 * Register Student Step1
 * Validate student data for each step
 */
export const registerStudentStep1Mutation = (
  options?: Partial<Options<RegisterStudentStep1Data>>,
): UseMutationOptions<
  RegisterStudentStep1Response,
  AxiosError<RegisterStudentStep1Error>,
  Options<RegisterStudentStep1Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterStudentStep1Response,
    AxiosError<RegisterStudentStep1Error>,
    Options<RegisterStudentStep1Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerStudentStep1({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerStudentStep2QueryKey = (
  options: Options<RegisterStudentStep2Data>,
) => createQueryKey("registerStudentStep2", options);

/**
 * Register Student Step2
 * Validate student data for each step
 */
export const registerStudentStep2Options = (
  options: Options<RegisterStudentStep2Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerStudentStep2({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerStudentStep2QueryKey(options),
  });
};

/**
 * Register Student Step2
 * Validate student data for each step
 */
export const registerStudentStep2Mutation = (
  options?: Partial<Options<RegisterStudentStep2Data>>,
): UseMutationOptions<
  RegisterStudentStep2Response,
  AxiosError<RegisterStudentStep2Error>,
  Options<RegisterStudentStep2Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterStudentStep2Response,
    AxiosError<RegisterStudentStep2Error>,
    Options<RegisterStudentStep2Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerStudentStep2({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerStudentStep3QueryKey = (
  options: Options<RegisterStudentStep3Data>,
) => createQueryKey("registerStudentStep3", options);

/**
 * Register Student Step3
 * Validate student data for each step
 */
export const registerStudentStep3Options = (
  options: Options<RegisterStudentStep3Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerStudentStep3({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerStudentStep3QueryKey(options),
  });
};

/**
 * Register Student Step3
 * Validate student data for each step
 */
export const registerStudentStep3Mutation = (
  options?: Partial<Options<RegisterStudentStep3Data>>,
): UseMutationOptions<
  RegisterStudentStep3Response,
  AxiosError<RegisterStudentStep3Error>,
  Options<RegisterStudentStep3Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterStudentStep3Response,
    AxiosError<RegisterStudentStep3Error>,
    Options<RegisterStudentStep3Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerStudentStep3({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerStudentStep4QueryKey = (
  options: Options<RegisterStudentStep4Data>,
) => createQueryKey("registerStudentStep4", options);

/**
 * Register Student Step4
 * Validate student data for each step
 */
export const registerStudentStep4Options = (
  options: Options<RegisterStudentStep4Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerStudentStep4({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerStudentStep4QueryKey(options),
  });
};

/**
 * Register Student Step4
 * Validate student data for each step
 */
export const registerStudentStep4Mutation = (
  options?: Partial<Options<RegisterStudentStep4Data>>,
): UseMutationOptions<
  RegisterStudentStep4Response,
  AxiosError<RegisterStudentStep4Error>,
  Options<RegisterStudentStep4Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterStudentStep4Response,
    AxiosError<RegisterStudentStep4Error>,
    Options<RegisterStudentStep4Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerStudentStep4({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerStudentStep5QueryKey = (
  options: Options<RegisterStudentStep5Data>,
) => createQueryKey("registerStudentStep5", options);

/**
 * Register Student Step5
 * Validate student data for each step
 */
export const registerStudentStep5Options = (
  options: Options<RegisterStudentStep5Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerStudentStep5({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerStudentStep5QueryKey(options),
  });
};

/**
 * Register Student Step5
 * Validate student data for each step
 */
export const registerStudentStep5Mutation = (
  options?: Partial<Options<RegisterStudentStep5Data>>,
): UseMutationOptions<
  RegisterStudentStep5Response,
  AxiosError<RegisterStudentStep5Error>,
  Options<RegisterStudentStep5Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterStudentStep5Response,
    AxiosError<RegisterStudentStep5Error>,
    Options<RegisterStudentStep5Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerStudentStep5({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerNewStudentQueryKey = (
  options: Options<RegisterNewStudentData>,
) => createQueryKey("registerNewStudent", options);

/**
 * Register New Student
 * Registers a new student in the system.
 */
export const registerNewStudentOptions = (
  options: Options<RegisterNewStudentData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerNewStudent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerNewStudentQueryKey(options),
  });
};

/**
 * Register New Student
 * Registers a new student in the system.
 */
export const registerNewStudentMutation = (
  options?: Partial<Options<RegisterNewStudentData>>,
): UseMutationOptions<
  RegisterNewStudentResponse,
  AxiosError<RegisterNewStudentError>,
  Options<RegisterNewStudentData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterNewStudentResponse,
    AxiosError<RegisterNewStudentError>,
    Options<RegisterNewStudentData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerNewStudent({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerEmployeeStep1QueryKey = (
  options: Options<RegisterEmployeeStep1Data>,
) => createQueryKey("registerEmployeeStep1", options);

/**
 * Register Employee Step1
 * Validate employee data for each step
 */
export const registerEmployeeStep1Options = (
  options: Options<RegisterEmployeeStep1Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerEmployeeStep1({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerEmployeeStep1QueryKey(options),
  });
};

/**
 * Register Employee Step1
 * Validate employee data for each step
 */
export const registerEmployeeStep1Mutation = (
  options?: Partial<Options<RegisterEmployeeStep1Data>>,
): UseMutationOptions<
  RegisterEmployeeStep1Response,
  AxiosError<RegisterEmployeeStep1Error>,
  Options<RegisterEmployeeStep1Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterEmployeeStep1Response,
    AxiosError<RegisterEmployeeStep1Error>,
    Options<RegisterEmployeeStep1Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerEmployeeStep1({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerEmployeeStep2QueryKey = (
  options: Options<RegisterEmployeeStep2Data>,
) => createQueryKey("registerEmployeeStep2", options);

/**
 * Register Employee Step2
 * Validate employee data for each step
 */
export const registerEmployeeStep2Options = (
  options: Options<RegisterEmployeeStep2Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerEmployeeStep2({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerEmployeeStep2QueryKey(options),
  });
};

/**
 * Register Employee Step2
 * Validate employee data for each step
 */
export const registerEmployeeStep2Mutation = (
  options?: Partial<Options<RegisterEmployeeStep2Data>>,
): UseMutationOptions<
  RegisterEmployeeStep2Response,
  AxiosError<RegisterEmployeeStep2Error>,
  Options<RegisterEmployeeStep2Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterEmployeeStep2Response,
    AxiosError<RegisterEmployeeStep2Error>,
    Options<RegisterEmployeeStep2Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerEmployeeStep2({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerEmployeeStep3QueryKey = (
  options: Options<RegisterEmployeeStep3Data>,
) => createQueryKey("registerEmployeeStep3", options);

/**
 * Register Employee Step3
 * Validate employee data for each step
 */
export const registerEmployeeStep3Options = (
  options: Options<RegisterEmployeeStep3Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerEmployeeStep3({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerEmployeeStep3QueryKey(options),
  });
};

/**
 * Register Employee Step3
 * Validate employee data for each step
 */
export const registerEmployeeStep3Mutation = (
  options?: Partial<Options<RegisterEmployeeStep3Data>>,
): UseMutationOptions<
  RegisterEmployeeStep3Response,
  AxiosError<RegisterEmployeeStep3Error>,
  Options<RegisterEmployeeStep3Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterEmployeeStep3Response,
    AxiosError<RegisterEmployeeStep3Error>,
    Options<RegisterEmployeeStep3Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerEmployeeStep3({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerEmployeeStep4QueryKey = (
  options: Options<RegisterEmployeeStep4Data>,
) => createQueryKey("registerEmployeeStep4", options);

/**
 * Register Employee Step4
 * Validate employee data for each step
 */
export const registerEmployeeStep4Options = (
  options: Options<RegisterEmployeeStep4Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerEmployeeStep4({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerEmployeeStep4QueryKey(options),
  });
};

/**
 * Register Employee Step4
 * Validate employee data for each step
 */
export const registerEmployeeStep4Mutation = (
  options?: Partial<Options<RegisterEmployeeStep4Data>>,
): UseMutationOptions<
  RegisterEmployeeStep4Response,
  AxiosError<RegisterEmployeeStep4Error>,
  Options<RegisterEmployeeStep4Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterEmployeeStep4Response,
    AxiosError<RegisterEmployeeStep4Error>,
    Options<RegisterEmployeeStep4Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerEmployeeStep4({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerEmployeeStep5QueryKey = (
  options: Options<RegisterEmployeeStep5Data>,
) => createQueryKey("registerEmployeeStep5", options);

/**
 * Register Employee Step5
 * Validate employee data for each step
 */
export const registerEmployeeStep5Options = (
  options: Options<RegisterEmployeeStep5Data>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerEmployeeStep5({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerEmployeeStep5QueryKey(options),
  });
};

/**
 * Register Employee Step5
 * Validate employee data for each step
 */
export const registerEmployeeStep5Mutation = (
  options?: Partial<Options<RegisterEmployeeStep5Data>>,
): UseMutationOptions<
  RegisterEmployeeStep5Response,
  AxiosError<RegisterEmployeeStep5Error>,
  Options<RegisterEmployeeStep5Data>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterEmployeeStep5Response,
    AxiosError<RegisterEmployeeStep5Error>,
    Options<RegisterEmployeeStep5Data>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerEmployeeStep5({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const registerNewEmployeeQueryKey = (
  options: Options<RegisterNewEmployeeData>,
) => createQueryKey("registerNewEmployee", options);

/**
 * Register New Employee
 * Registers a new user (Admin, Student, Employee) in the system.
 */
export const registerNewEmployeeOptions = (
  options: Options<RegisterNewEmployeeData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await registerNewEmployee({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: registerNewEmployeeQueryKey(options),
  });
};

/**
 * Register New Employee
 * Registers a new user (Admin, Student, Employee) in the system.
 */
export const registerNewEmployeeMutation = (
  options?: Partial<Options<RegisterNewEmployeeData>>,
): UseMutationOptions<
  RegisterNewEmployeeResponse,
  AxiosError<RegisterNewEmployeeError>,
  Options<RegisterNewEmployeeData>
> => {
  const mutationOptions: UseMutationOptions<
    RegisterNewEmployeeResponse,
    AxiosError<RegisterNewEmployeeError>,
    Options<RegisterNewEmployeeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await registerNewEmployee({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getYearsQueryKey = (options?: Options<GetYearsData>) =>
  createQueryKey("getYears", options);

/**
 * Get Years
 * Returns a list of all academic years in the system.
 */
export const getYearsOptions = (options?: Options<GetYearsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getYears({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getYearsQueryKey(options),
  });
};

export const postYearQueryKey = (options: Options<PostYearData>) =>
  createQueryKey("postYear", options);

/**
 * Post Year
 * Creates a new Year
 */
export const postYearOptions = (options: Options<PostYearData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postYear({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postYearQueryKey(options),
  });
};

/**
 * Post Year
 * Creates a new Year
 */
export const postYearMutation = (
  options?: Partial<Options<PostYearData>>,
): UseMutationOptions<
  PostYearResponse,
  AxiosError<PostYearError>,
  Options<PostYearData>
> => {
  const mutationOptions: UseMutationOptions<
    PostYearResponse,
    AxiosError<PostYearError>,
    Options<PostYearData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postYear({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getYearSummaryQueryKey = (options?: Options<GetYearSummaryData>) =>
  createQueryKey("getYearSummary", options);

/**
 * Get Year Summary
 * Returns a list of all academic years in the system.
 */
export const getYearSummaryOptions = (
  options?: Options<GetYearSummaryData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getYearSummary({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getYearSummaryQueryKey(options),
  });
};

/**
 * Delete Year
 * Deletes an existing academic year in the system.
 */
export const deleteYearMutation = (
  options?: Partial<Options<DeleteYearData>>,
): UseMutationOptions<
  DeleteYearResponse,
  AxiosError<DeleteYearError>,
  Options<DeleteYearData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteYearResponse,
    AxiosError<DeleteYearError>,
    Options<DeleteYearData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteYear({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getYearByIdQueryKey = (options: Options<GetYearByIdData>) =>
  createQueryKey("getYearById", options);

/**
 * Get Year By Id
 * Returns specific academic year
 */
export const getYearByIdOptions = (options: Options<GetYearByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getYearById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getYearByIdQueryKey(options),
  });
};

export const getDetailGradesByYearIdQueryKey = (
  options: Options<GetDetailGradesByYearIdData>,
) => createQueryKey("getDetailGradesByYearId", options);

/**
 * Get Detail Grades By Year Id
 * Returns specific academic year
 */
export const getDetailGradesByYearIdOptions = (
  options: Options<GetDetailGradesByYearIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDetailGradesByYearId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDetailGradesByYearIdQueryKey(options),
  });
};

export const getDetailSubjectsByYearIdQueryKey = (
  options: Options<GetDetailSubjectsByYearIdData>,
) => createQueryKey("getDetailSubjectsByYearId", options);

/**
 * Get Detail Subjects By Year Id
 * Returns specific academic year
 */
export const getDetailSubjectsByYearIdOptions = (
  options: Options<GetDetailSubjectsByYearIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getDetailSubjectsByYearId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getDetailSubjectsByYearIdQueryKey(options),
  });
};

export const getGradesQueryKey = (options: Options<GetGradesData>) =>
  createQueryKey("getGrades", options);

/**
 * Get Grades
 * Returns specific academic year
 */
export const getGradesOptions = (options: Options<GetGradesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGrades({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGradesQueryKey(options),
  });
};

export const postGradeQueryKey = (options: Options<PostGradeData>) =>
  createQueryKey("postGrade", options);

/**
 * Post Grade
 * Creates a new Grade
 */
export const postGradeOptions = (options: Options<PostGradeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postGrade({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postGradeQueryKey(options),
  });
};

/**
 * Post Grade
 * Creates a new Grade
 */
export const postGradeMutation = (
  options?: Partial<Options<PostGradeData>>,
): UseMutationOptions<
  PostGradeResponse,
  AxiosError<PostGradeError>,
  Options<PostGradeData>
> => {
  const mutationOptions: UseMutationOptions<
    PostGradeResponse,
    AxiosError<PostGradeError>,
    Options<PostGradeData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postGrade({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getGradesSetupQueryKey = (options: Options<GetGradesSetupData>) =>
  createQueryKey("getGradesSetup", options);

/**
 * Get Grades Setup
 * Returns specific academic year
 */
export const getGradesSetupOptions = (options: Options<GetGradesSetupData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGradesSetup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGradesSetupQueryKey(options),
  });
};

export const getGradesSetupByIdQueryKey = (
  options: Options<GetGradesSetupByIdData>,
) => createQueryKey("getGradesSetupById", options);

/**
 * Get Grades Setup By Id
 * Returns specific Grade SetUp
 */
export const getGradesSetupByIdOptions = (
  options: Options<GetGradesSetupByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGradesSetupById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGradesSetupByIdQueryKey(options),
  });
};

/**
 * Patch Grade Setup
 * Updates specific Grade SetUp
 */
export const patchGradeSetupMutation = (
  options?: Partial<Options<PatchGradeSetupData>>,
): UseMutationOptions<
  PatchGradeSetupResponse,
  AxiosError<PatchGradeSetupError>,
  Options<PatchGradeSetupData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchGradeSetupResponse,
    AxiosError<PatchGradeSetupError>,
    Options<PatchGradeSetupData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchGradeSetup({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getGradeByIdQueryKey = (options: Options<GetGradeByIdData>) =>
  createQueryKey("getGradeById", options);

/**
 * Get Grade By Id
 * Returns specific academic grade
 */
export const getGradeByIdOptions = (options: Options<GetGradeByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getGradeById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getGradeByIdQueryKey(options),
  });
};

export const getSubjectsQueryKey = (options: Options<GetSubjectsData>) =>
  createQueryKey("getSubjects", options);

/**
 * Get Subjects
 * Returns All Subjects with in academic year
 */
export const getSubjectsOptions = (options: Options<GetSubjectsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSubjects({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSubjectsQueryKey(options),
  });
};

export const postSubjectQueryKey = (options: Options<PostSubjectData>) =>
  createQueryKey("postSubject", options);

/**
 * Post Subject
 * Creates a new Subject
 */
export const postSubjectOptions = (options: Options<PostSubjectData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await postSubject({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: postSubjectQueryKey(options),
  });
};

/**
 * Post Subject
 * Creates a new Subject
 */
export const postSubjectMutation = (
  options?: Partial<Options<PostSubjectData>>,
): UseMutationOptions<
  PostSubjectResponse,
  AxiosError<PostSubjectError>,
  Options<PostSubjectData>
> => {
  const mutationOptions: UseMutationOptions<
    PostSubjectResponse,
    AxiosError<PostSubjectError>,
    Options<PostSubjectData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await postSubject({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSubjectsSetupQueryKey = (
  options: Options<GetSubjectsSetupData>,
) => createQueryKey("getSubjectsSetup", options);

/**
 * Get Subjects Setup
 * Returns All Subjects with in academic year
 */
export const getSubjectsSetupOptions = (
  options: Options<GetSubjectsSetupData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSubjectsSetup({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSubjectsSetupQueryKey(options),
  });
};

export const getSubjectSetupByIdQueryKey = (
  options: Options<GetSubjectSetupByIdData>,
) => createQueryKey("getSubjectSetupById", options);

/**
 * Get Subject Setup By Id
 * Returns specific academic subject
 */
export const getSubjectSetupByIdOptions = (
  options: Options<GetSubjectSetupByIdData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSubjectSetupById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSubjectSetupByIdQueryKey(options),
  });
};

/**
 * Patch Subject Setup
 * Updates Subject SetUp
 */
export const patchSubjectSetupMutation = (
  options?: Partial<Options<PatchSubjectSetupData>>,
): UseMutationOptions<
  PatchSubjectSetupResponse,
  AxiosError<PatchSubjectSetupError>,
  Options<PatchSubjectSetupData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchSubjectSetupResponse,
    AxiosError<PatchSubjectSetupError>,
    Options<PatchSubjectSetupData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await patchSubjectSetup({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getSubjectByIdQueryKey = (options: Options<GetSubjectByIdData>) =>
  createQueryKey("getSubjectById", options);

/**
 * Get Subject By Id
 * Returns specific academic subject
 */
export const getSubjectByIdOptions = (options: Options<GetSubjectByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSubjectById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSubjectByIdQueryKey(options),
  });
};

export const getStreamsQueryKey = (options: Options<GetStreamsData>) =>
  createQueryKey("getStreams", options);

/**
 * Get Streams
 * Returns specific academic grade
 */
export const getStreamsOptions = (options: Options<GetStreamsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStreams({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStreamsQueryKey(options),
  });
};

export const getStreamByIdQueryKey = (options: Options<GetStreamByIdData>) =>
  createQueryKey("getStreamById", options);

/**
 * Get Stream By Id
 * Returns specific academic stream
 */
export const getStreamByIdOptions = (options: Options<GetStreamByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStreamById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStreamByIdQueryKey(options),
  });
};

export const getSectionsQueryKey = (options: Options<GetSectionsData>) =>
  createQueryKey("getSections", options);

/**
 * Get Sections
 * Returns specific academic grade
 */
export const getSectionsOptions = (options: Options<GetSectionsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSections({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSectionsQueryKey(options),
  });
};

export const getSectionByIdQueryKey = (options: Options<GetSectionByIdData>) =>
  createQueryKey("getSectionById", options);

/**
 * Get Section By Id
 * Returns specific academic section
 */
export const getSectionByIdOptions = (options: Options<GetSectionByIdData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getSectionById({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getSectionByIdQueryKey(options),
  });
};

export const getLoggedInUserQueryKey = (
  options?: Options<GetLoggedInUserData>,
) => createQueryKey("getLoggedInUser", options);

/**
 * Get Logged In User
 * Returns the current logged in user information.
 */
export const getLoggedInUserOptions = (
  options?: Options<GetLoggedInUserData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getLoggedInUser({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getLoggedInUserQueryKey(options),
  });
};

export const getAdminBasicInfoQueryKey = (
  options?: Options<GetAdminBasicInfoData>,
) => createQueryKey("getAdminBasicInfo", options);

/**
 * Get Admin Basic Info
 * Returns the current logged in user information.
 */
export const getAdminBasicInfoOptions = (
  options?: Options<GetAdminBasicInfoData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminBasicInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getAdminBasicInfoQueryKey(options),
  });
};

export const getTeacherBasicInfoQueryKey = (
  options?: Options<GetTeacherBasicInfoData>,
) => createQueryKey("getTeacherBasicInfo", options);

/**
 * Get Teacher Basic Info
 * Returns the current logged in user information.
 */
export const getTeacherBasicInfoOptions = (
  options?: Options<GetTeacherBasicInfoData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeacherBasicInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeacherBasicInfoQueryKey(options),
  });
};

export const getStudentBasicInfoQueryKey = (
  options?: Options<GetStudentBasicInfoData>,
) => createQueryKey("getStudentBasicInfo", options);

/**
 * Get Student Basic Info
 * Returns the current logged in user information.
 */
export const getStudentBasicInfoOptions = (
  options?: Options<GetStudentBasicInfoData>,
) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStudentBasicInfo({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStudentBasicInfoQueryKey(options),
  });
};

/**
 * Delete Students
 * This endpoint will delete students based on the provided IDs.
 */
export const deleteStudentsMutation = (
  options?: Partial<Options<DeleteStudentsData>>,
): UseMutationOptions<
  DeleteStudentsResponse,
  AxiosError<DeleteStudentsError>,
  Options<DeleteStudentsData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteStudentsResponse,
    AxiosError<DeleteStudentsError>,
    Options<DeleteStudentsData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteStudents({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getStudentsQueryKey = (options: Options<GetStudentsData>) =>
  createQueryKey("getStudents", options);

/**
 * Get Students
 * This endpoint will return students based on the provided filters.
 */
export const getStudentsOptions = (options: Options<GetStudentsData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStudents({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStudentsQueryKey(options),
  });
};

export const getStudentQueryKey = (options: Options<GetStudentData>) =>
  createQueryKey("getStudent", options);

/**
 * Get Student
 * This endpoint will return a student based on the provided ID.
 */
export const getStudentOptions = (options: Options<GetStudentData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getStudent({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getStudentQueryKey(options),
  });
};

/**
 * Update Student Status
 * This endpoint will patch students based on the provided IDs.
 */
export const updateStudentStatusMutation = (
  options?: Partial<Options<UpdateStudentStatusData>>,
): UseMutationOptions<
  UpdateStudentStatusResponse,
  AxiosError<UpdateStudentStatusError>,
  Options<UpdateStudentStatusData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateStudentStatusResponse,
    AxiosError<UpdateStudentStatusError>,
    Options<UpdateStudentStatusData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateStudentStatus({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

/**
 * Delete Employees
 * This endpoint will delete employees by their IDs.
 */
export const deleteEmployeesMutation = (
  options?: Partial<Options<DeleteEmployeesData>>,
): UseMutationOptions<
  DeleteEmployeesResponse,
  AxiosError<DeleteEmployeesError>,
  Options<DeleteEmployeesData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteEmployeesResponse,
    AxiosError<DeleteEmployeesError>,
    Options<DeleteEmployeesData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await deleteEmployees({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getEmployeesQueryKey = (options?: Options<GetEmployeesData>) =>
  createQueryKey("getEmployees", options);

/**
 * Get Employees
 * This endpoint will return employees based on the provided filters.
 */
export const getEmployeesOptions = (options?: Options<GetEmployeesData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEmployees({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEmployeesQueryKey(options),
  });
};

export const getEmployeeQueryKey = (options: Options<GetEmployeeData>) =>
  createQueryKey("getEmployee", options);

/**
 * Get Employee
 * This endpoint will return a single employee by ID.
 */
export const getEmployeeOptions = (options: Options<GetEmployeeData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getEmployee({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getEmployeeQueryKey(options),
  });
};

/**
 * Update Employee Status
 * This endpoint will update the status of employees by their IDs.
 */
export const updateEmployeeStatusMutation = (
  options?: Partial<Options<UpdateEmployeeStatusData>>,
): UseMutationOptions<
  UpdateEmployeeStatusResponse,
  AxiosError<UpdateEmployeeStatusError>,
  Options<UpdateEmployeeStatusData>
> => {
  const mutationOptions: UseMutationOptions<
    UpdateEmployeeStatusResponse,
    AxiosError<UpdateEmployeeStatusError>,
    Options<UpdateEmployeeStatusData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await updateEmployeeStatus({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const getTeachersQueryKey = (options?: Options<GetTeachersData>) =>
  createQueryKey("getTeachers", options);

/**
 * Get Teachers
 * This endpoint will return employees based on the provided filters.
 */
export const getTeachersOptions = (options?: Options<GetTeachersData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getTeachers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: getTeachersQueryKey(options),
  });
};

export const assignTeacherQueryKey = (options: Options<AssignTeacherData>) =>
  createQueryKey("assignTeacher", options);

/**
 * Assign Teacher
 * This endpoint will assign a teacher to
 * - academic term
 * - grade stream subject
 * - section
 */
export const assignTeacherOptions = (options: Options<AssignTeacherData>) => {
  return queryOptions({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await assignTeacher({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: assignTeacherQueryKey(options),
  });
};

/**
 * Assign Teacher
 * This endpoint will assign a teacher to
 * - academic term
 * - grade stream subject
 * - section
 */
export const assignTeacherMutation = (
  options?: Partial<Options<AssignTeacherData>>,
): UseMutationOptions<
  AssignTeacherResponse,
  AxiosError<AssignTeacherError>,
  Options<AssignTeacherData>
> => {
  const mutationOptions: UseMutationOptions<
    AssignTeacherResponse,
    AxiosError<AssignTeacherError>,
    Options<AssignTeacherData>
  > = {
    mutationFn: async (localOptions) => {
      const { data } = await assignTeacher({
        ...options,
        ...localOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
