export { default as AdminHeader } from './AdminHeader';
export { default as AdminPanel } from './AdminPanel';
export { default as TeacherHeader } from './TeachHeader';
export { default as TeacherPanel } from './TeachPanel';
export { default as StudentHeader } from './StudHeader';
export { default as StudentPanel } from './StudPanel';
export { default as AdminLayout } from './AdminLayout';
export { default as TeacherLayout } from './TeachLayout';
export { default as StudentLayout } from './StudLayout';
