version: "3.8"

services:
  db:
    image: ghcr.io/rekebuba/db:latest
    ports:
      - "3306:3306"

  backend:
    image: ghcr.io/rekebuba/backend:latest
    depends_on:
      - db
    environment:
      MYSQL_DOCKER_HOST: $MYSQL_DOCKER_HOST

      TEST_ADMIN_JWT_SECRET: $TEST_ADMIN_JWT_SECRET 
      TEST_TEACHER_JWT_SECRET: $TEST_TEACHER_JWT_SECRET
      TEST_STUDENT_JWT_SECRET: $TEST_STUDENT_JWT_SECRET
      
      TEST_MYSQL_USER: $TEST_MYSQL_USER
      TEST_MYSQL_PWD: $TEST_MYSQL_PWD
      TEST_MYSQL_DB: $TEST_MYSQL_DB

    command: >
      bash -c "pytest --junitxml=test-reports/results.xml --cov=your_module --cov-report=xml"
