name: Run Tests via Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  IMAGE_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull images
        run: |
          docker pull ghcr.io/rekebuba/backend:${{ env.IMAGE_TAG }}
          docker pull ghcr.io/rekebuba/db:${{ env.IMAGE_TAG }}

      - name: Run tests
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          TEST_ADMIN_JWT_SECRET: ${{ secrets.TEST_ADMIN_JWT_SECRET }}
          TEST_TEACHER_JWT_SECRET: ${{ secrets.TEST_TEACHER_JWT_SECRET }}
          TEST_STUDENT_JWT_SECRET: ${{ secrets.TEST_STUDENT_JWT_SECRET }}
          TEST_MYSQL_USER: ${{ secrets.TEST_MYSQL_USER }}
          TEST_MYSQL_PWD: ${{ secrets.TEST_MYSQL_PWD }}
          TEST_MYSQL_DB: ${{ secrets.TEST_MYSQL_DB }}
        run: |
          docker compose -f docker-compose.test.yml up \
            --abort-on-container-exit \
            --exit-code-from backend \
            --build

      # - name: Upload test results
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: test-results
      #     path: test-reports/
      #     retention-days: 15
