// This file is auto-generated by @hey-api/openapi-ts

import {
  type Options as ClientOptions,
  type TDataShape,
  type Client,
  urlSearchParamsBodySerializer,
} from "./client";
import type {
  LoginData,
  LoginResponses,
  LoginErrors,
  LogoutData,
  LogoutResponses,
  RegisterNewAdminData,
  RegisterNewAdminResponses,
  RegisterNewAdminErrors,
  RegisterNewStudentData,
  RegisterNewStudentResponses,
  RegisterNewStudentErrors,
  RegisterNewTeacherData,
  RegisterNewTeacherResponses,
  RegisterNewTeacherErrors,
  GetYearsData,
  GetYearsResponses,
  PostYearData,
  PostYearResponses,
  PostYearErrors,
  GetYearSummaryData,
  GetYearSummaryResponses,
  GetYearSummaryErrors,
  DeleteYearData,
  DeleteYearResponses,
  DeleteYearErrors,
  GetYearByIdData,
  GetYearByIdResponses,
  GetYearByIdErrors,
  GetDetailGradesByYearIdData,
  GetDetailGradesByYearIdResponses,
  GetDetailGradesByYearIdErrors,
  GetDetailSubjectsByYearIdData,
  GetDetailSubjectsByYearIdResponses,
  GetDetailSubjectsByYearIdErrors,
  GetGradesData,
  GetGradesResponses,
  GetGradesErrors,
  PostGradeData,
  PostGradeResponses,
  PostGradeErrors,
  GetGradesSetupData,
  GetGradesSetupResponses,
  GetGradesSetupErrors,
  GetGradesSetupByIdData,
  GetGradesSetupByIdResponses,
  GetGradesSetupByIdErrors,
  PatchGradeSetupData,
  PatchGradeSetupResponses,
  PatchGradeSetupErrors,
  GetGradeByIdData,
  GetGradeByIdResponses,
  GetGradeByIdErrors,
  GetSubjectsData,
  GetSubjectsResponses,
  GetSubjectsErrors,
  PostSubjectData,
  PostSubjectResponses,
  PostSubjectErrors,
  GetSubjectsSetupData,
  GetSubjectsSetupResponses,
  GetSubjectsSetupErrors,
  GetSubjectSetupByIdData,
  GetSubjectSetupByIdResponses,
  GetSubjectSetupByIdErrors,
  PatchSubjectSetupData,
  PatchSubjectSetupResponses,
  PatchSubjectSetupErrors,
  GetSubjectByIdData,
  GetSubjectByIdResponses,
  GetSubjectByIdErrors,
  GetStreamsData,
  GetStreamsResponses,
  GetStreamsErrors,
  GetStreamByIdData,
  GetStreamByIdResponses,
  GetStreamByIdErrors,
  GetSectionsData,
  GetSectionsResponses,
  GetSectionsErrors,
  GetSectionByIdData,
  GetSectionByIdResponses,
  GetSectionByIdErrors,
  GetLoggedInUserData,
  GetLoggedInUserResponses,
  GetAdminBasicInfoData,
  GetAdminBasicInfoResponses,
  GetTeacherBasicInfoData,
  GetTeacherBasicInfoResponses,
  GetStudentBasicInfoData,
  GetStudentBasicInfoResponses,
} from "./types.gen";
import {
  zLoginResponse,
  zLogoutResponse,
  zRegisterNewAdminResponse,
  zRegisterNewStudentResponse,
  zRegisterNewTeacherResponse,
  zGetYearsResponse,
  zPostYearResponse,
  zGetYearSummaryResponse,
  zDeleteYearResponse,
  zGetYearByIdResponse,
  zGetDetailGradesByYearIdResponse,
  zGetDetailSubjectsByYearIdResponse,
  zGetGradesResponse,
  zPostGradeResponse,
  zGetGradesSetupResponse,
  zGetGradesSetupByIdResponse,
  zPatchGradeSetupResponse,
  zGetGradeByIdResponse,
  zGetSubjectsResponse,
  zPostSubjectResponse,
  zGetSubjectsSetupResponse,
  zGetSubjectSetupByIdResponse,
  zPatchSubjectSetupResponse,
  zGetSubjectByIdResponse,
  zGetStreamsResponse,
  zGetStreamByIdResponse,
  zGetSectionsResponse,
  zGetSectionByIdResponse,
  zGetLoggedInUserResponse,
  zGetAdminBasicInfoResponse,
  zGetTeacherBasicInfoResponse,
  zGetStudentBasicInfoResponse,
} from "./zod.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Login
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    LoginResponses,
    LoginErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: "json",
    responseValidator: async (data) => {
      return await zLoginResponse.parseAsync(data);
    },
    url: "/api/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options.headers,
    },
  });
};

/**
 * Logout
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).post<
    LogoutResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zLogoutResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/auth/logout",
    ...options,
  });
};

/**
 * Register New Admin
 * Registers a new admin in the system.
 */
export const registerNewAdmin = <ThrowOnError extends boolean = false>(
  options: Options<RegisterNewAdminData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RegisterNewAdminResponses,
    RegisterNewAdminErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zRegisterNewAdminResponse.parseAsync(data);
    },
    url: "/api/v1/register/admins",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Register New Student
 * Registers a new student in the system.
 */
export const registerNewStudent = <ThrowOnError extends boolean = false>(
  options: Options<RegisterNewStudentData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RegisterNewStudentResponses,
    RegisterNewStudentErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zRegisterNewStudentResponse.parseAsync(data);
    },
    url: "/api/v1/register/students",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Register New Teacher
 * Registers a new user (Admin, Student, Teacher) in the system.
 */
export const registerNewTeacher = <ThrowOnError extends boolean = false>(
  options: Options<RegisterNewTeacherData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    RegisterNewTeacherResponses,
    RegisterNewTeacherErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zRegisterNewTeacherResponse.parseAsync(data);
    },
    url: "/api/v1/register/teachers",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Years
 * Returns a list of all academic years in the system.
 */
export const getYears = <ThrowOnError extends boolean = false>(
  options?: Options<GetYearsData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetYearsResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetYearsResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/years/",
    ...options,
  });
};

/**
 * Post Year
 * Creates a new Year
 */
export const postYear = <ThrowOnError extends boolean = false>(
  options: Options<PostYearData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostYearResponses,
    PostYearErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zPostYearResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/years/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Year Summary
 * Returns a list of all academic years in the system.
 */
export const getYearSummary = <ThrowOnError extends boolean = false>(
  options?: Options<GetYearSummaryData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetYearSummaryResponses,
    GetYearSummaryErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetYearSummaryResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/years/summary",
    ...options,
  });
};

/**
 * Delete Year
 * Deletes an existing academic year in the system.
 */
export const deleteYear = <ThrowOnError extends boolean = false>(
  options: Options<DeleteYearData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).delete<
    DeleteYearResponses,
    DeleteYearErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zDeleteYearResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/years/{year_id}",
    ...options,
  });
};

/**
 * Get Year By Id
 * Returns specific academic year
 */
export const getYearById = <ThrowOnError extends boolean = false>(
  options: Options<GetYearByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetYearByIdResponses,
    GetYearByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetYearByIdResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/years/{year_id}",
    ...options,
  });
};

/**
 * Get Detail Grades By Year Id
 * Returns specific academic year
 */
export const getDetailGradesByYearId = <ThrowOnError extends boolean = false>(
  options: Options<GetDetailGradesByYearIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDetailGradesByYearIdResponses,
    GetDetailGradesByYearIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetDetailGradesByYearIdResponse.parseAsync(data);
    },
    url: "/api/v1/years/{year_id}/grades/detail",
    ...options,
  });
};

/**
 * Get Detail Subjects By Year Id
 * Returns specific academic year
 */
export const getDetailSubjectsByYearId = <ThrowOnError extends boolean = false>(
  options: Options<GetDetailSubjectsByYearIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetDetailSubjectsByYearIdResponses,
    GetDetailSubjectsByYearIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetDetailSubjectsByYearIdResponse.parseAsync(data);
    },
    url: "/api/v1/years/{year_id}/subjects/detail",
    ...options,
  });
};

/**
 * Get Grades
 * Returns specific academic year
 */
export const getGrades = <ThrowOnError extends boolean = false>(
  options: Options<GetGradesData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetGradesResponses,
    GetGradesErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetGradesResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/grades/",
    ...options,
  });
};

/**
 * Post Grade
 * Creates a new Grade
 */
export const postGrade = <ThrowOnError extends boolean = false>(
  options: Options<PostGradeData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostGradeResponses,
    PostGradeErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zPostGradeResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/grades/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Grades Setup
 * Returns specific academic year
 */
export const getGradesSetup = <ThrowOnError extends boolean = false>(
  options: Options<GetGradesSetupData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetGradesSetupResponses,
    GetGradesSetupErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetGradesSetupResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/grades/setup",
    ...options,
  });
};

/**
 * Get Grades Setup By Id
 * Returns specific Grade SetUp
 */
export const getGradesSetupById = <ThrowOnError extends boolean = false>(
  options: Options<GetGradesSetupByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetGradesSetupByIdResponses,
    GetGradesSetupByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetGradesSetupByIdResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/grades/setup/{grade_id}",
    ...options,
  });
};

/**
 * Patch Grade Setup
 * Updates specific Grade SetUp
 */
export const patchGradeSetup = <ThrowOnError extends boolean = false>(
  options: Options<PatchGradeSetupData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchGradeSetupResponses,
    PatchGradeSetupErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zPatchGradeSetupResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/grades/setup/{grade_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Grade By Id
 * Returns specific academic grade
 */
export const getGradeById = <ThrowOnError extends boolean = false>(
  options: Options<GetGradeByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetGradeByIdResponses,
    GetGradeByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetGradeByIdResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/grades/{grade_id}",
    ...options,
  });
};

/**
 * Get Subjects
 * Returns All Subjects with in academic year
 */
export const getSubjects = <ThrowOnError extends boolean = false>(
  options: Options<GetSubjectsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetSubjectsResponses,
    GetSubjectsErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetSubjectsResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/subjects/",
    ...options,
  });
};

/**
 * Post Subject
 * Creates a new Subject
 */
export const postSubject = <ThrowOnError extends boolean = false>(
  options: Options<PostSubjectData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostSubjectResponses,
    PostSubjectErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zPostSubjectResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/subjects/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Subjects Setup
 * Returns All Subjects with in academic year
 */
export const getSubjectsSetup = <ThrowOnError extends boolean = false>(
  options: Options<GetSubjectsSetupData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetSubjectsSetupResponses,
    GetSubjectsSetupErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetSubjectsSetupResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/subjects/setup",
    ...options,
  });
};

/**
 * Get Subject Setup By Id
 * Returns specific academic subject
 */
export const getSubjectSetupById = <ThrowOnError extends boolean = false>(
  options: Options<GetSubjectSetupByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetSubjectSetupByIdResponses,
    GetSubjectSetupByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetSubjectSetupByIdResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/subjects/setup/{subject_id}",
    ...options,
  });
};

/**
 * Patch Subject Setup
 * Updates Subject SetUp
 */
export const patchSubjectSetup = <ThrowOnError extends boolean = false>(
  options: Options<PatchSubjectSetupData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchSubjectSetupResponses,
    PatchSubjectSetupErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zPatchSubjectSetupResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/subjects/setup/{subject_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });
};

/**
 * Get Subject By Id
 * Returns specific academic subject
 */
export const getSubjectById = <ThrowOnError extends boolean = false>(
  options: Options<GetSubjectByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetSubjectByIdResponses,
    GetSubjectByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetSubjectByIdResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/subjects/{subject_id}",
    ...options,
  });
};

/**
 * Get Streams
 * Returns specific academic grade
 */
export const getStreams = <ThrowOnError extends boolean = false>(
  options: Options<GetStreamsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetStreamsResponses,
    GetStreamsErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetStreamsResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/streams/",
    ...options,
  });
};

/**
 * Get Stream By Id
 * Returns specific academic stream
 */
export const getStreamById = <ThrowOnError extends boolean = false>(
  options: Options<GetStreamByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetStreamByIdResponses,
    GetStreamByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetStreamByIdResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/streams/{stream_id}",
    ...options,
  });
};

/**
 * Get Sections
 * Returns specific academic grade
 */
export const getSections = <ThrowOnError extends boolean = false>(
  options: Options<GetSectionsData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetSectionsResponses,
    GetSectionsErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetSectionsResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sections/",
    ...options,
  });
};

/**
 * Get Section By Id
 * Returns specific academic section
 */
export const getSectionById = <ThrowOnError extends boolean = false>(
  options: Options<GetSectionByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetSectionByIdResponses,
    GetSectionByIdErrors,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetSectionByIdResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/sections/{section_id}",
    ...options,
  });
};

/**
 * Get Logged In User
 * Returns the current logged in user information.
 */
export const getLoggedInUser = <ThrowOnError extends boolean = false>(
  options?: Options<GetLoggedInUserData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetLoggedInUserResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetLoggedInUserResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/me/",
    ...options,
  });
};

/**
 * Get Admin Basic Info
 * Returns the current logged in user information.
 */
export const getAdminBasicInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetAdminBasicInfoData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetAdminBasicInfoResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetAdminBasicInfoResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/me/admin",
    ...options,
  });
};

/**
 * Get Teacher Basic Info
 * Returns the current logged in user information.
 */
export const getTeacherBasicInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetTeacherBasicInfoData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetTeacherBasicInfoResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetTeacherBasicInfoResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/me/teacher",
    ...options,
  });
};

/**
 * Get Student Basic Info
 * Returns the current logged in user information.
 */
export const getStudentBasicInfo = <ThrowOnError extends boolean = false>(
  options?: Options<GetStudentBasicInfoData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetStudentBasicInfoResponses,
    unknown,
    ThrowOnError
  >({
    responseType: "json",
    responseValidator: async (data) => {
      return await zGetStudentBasicInfoResponse.parseAsync(data);
    },
    security: [
      {
        scheme: "bearer",
        type: "http",
      },
    ],
    url: "/api/v1/me/student",
    ...options,
  });
};
