// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * AcademicTermEnum
 */
export const zAcademicTermEnum = z.enum(["1", "2", "3", "4"]);

/**
 * AcademicTermSchema
 * This model represents an academic term in the system.
 */
export const zAcademicTermSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  yearId: z.uuid(),
  name: zAcademicTermEnum,
  startDate: z.iso.date(),
  endDate: z.iso.date(),
  registrationStart: z.optional(z.union([z.iso.date(), z.null()])),
  registrationEnd: z.optional(z.union([z.iso.date(), z.null()])),
});

/**
 * AcademicTermTypeEnum
 */
export const zAcademicTermTypeEnum = z.enum(["Semester", "Quarter"]);

/**
 * AcademicYearStatusEnum
 */
export const zAcademicYearStatusEnum = z.enum([
  "upcoming",
  "active",
  "completed",
  "archived",
]);

/**
 * RoleEnum
 */
export const zRoleEnum = z.enum(["admin", "teacher", "student"]);

/**
 * GenderEnum
 */
export const zGenderEnum = z.enum(["male", "female"]);

/**
 * AdminSchema
 * This model represents an admin in the system. It inherits from BaseModel.
 */
export const zAdminSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  userId: z.optional(z.union([z.uuid(), z.null()])),
  firstName: z.string(),
  fatherName: z.string(),
  grandFatherName: z.string(),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  email: z.string(),
  phone: z.string(),
  address: z.string(),
});

/**
 * AdminInfo
 */
export const zAdminInfo = z.object({
  id: z.uuid(),
  identification: z.string(),
  role: zRoleEnum,
  imagePath: z.optional(z.union([z.string(), z.null()])),
  createdAt: z.iso.datetime(),
  admin: zAdminSchema,
});

/**
 * AssessmentSchema
 * This model represents an assessment record for a student including details
 */
export const zAssessmentSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  studentId: z.uuid(),
  studentTermRecordId: z.uuid(),
  yearlySubjectId: z.uuid(),
  total: z.optional(z.union([z.number(), z.null()])),
  rank: z.optional(z.union([z.int(), z.null()])),
});

/**
 * BloodTypeEnum
 */
export const zBloodTypeEnum = z.enum([
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
  "unknown",
]);

/**
 * Body_login_credential
 */
export const zBodyLoginCredential = z.object({
  grant_type: z.optional(z.union([z.string().regex(/^password$/), z.null()])),
  username: z.string(),
  password: z.string(),
  scope: z.optional(z.string()).default(""),
  client_id: z.optional(z.union([z.string(), z.null()])),
  client_secret: z.optional(z.union([z.string(), z.null()])),
});

/**
 * DeleteYearSuccess
 */
export const zDeleteYearSuccess = z.object({
  message: z.optional(z.string()).default("Year deleted Successfully"),
});

/**
 * EventEligibilityEnum
 */
export const zEventEligibilityEnum = z.enum([
  "all",
  "students only",
  "faculty only",
  "invitation only",
]);

/**
 * EventLocationEnum
 */
export const zEventLocationEnum = z.enum([
  "auditorium",
  "classroom",
  "sports field",
  "online",
  "other",
]);

/**
 * EventOrganizerEnum
 */
export const zEventOrganizerEnum = z.enum([
  "school",
  "school administration",
  "student club",
  "external organizer",
]);

/**
 * EventPurposeEnum
 */
export const zEventPurposeEnum = z.enum([
  "academic",
  "cultural",
  "sports",
  "graduation",
  "administration",
  "new semester",
  "other",
]);

/**
 * EventSchema
 * This model represents an event in the system.
 */
export const zEventSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  yearId: z.uuid(),
  title: z.string(),
  purpose: zEventPurposeEnum,
  organizer: zEventOrganizerEnum,
  startDate: z.iso.date(),
  endDate: z.iso.date(),
  startTime: z.iso.datetime(),
  endTime: z.iso.datetime(),
  location: z.optional(z.union([zEventLocationEnum, z.null()])),
  isHybrid: z.optional(z.boolean()).default(false),
  onlineLink: z.optional(z.union([z.string(), z.null()])),
  eligibility: z.optional(z.union([zEventEligibilityEnum, z.null()])),
  hasFee: z.optional(z.boolean()).default(false),
  feeAmount: z.optional(z.int()).default(0),
  description: z.optional(z.union([z.string(), z.null()])),
});

/**
 * ExperienceYearEnum
 */
export const zExperienceYearEnum = z.enum([
  "0",
  "1-2",
  "3-5",
  "6-10",
  "11-15",
  "16-20",
  "20+",
]);

/**
 * GradeEnum
 */
export const zGradeEnum = z.enum([
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
]);

/**
 * GradeLevelEnum
 */
export const zGradeLevelEnum = z.enum([
  "primary",
  "middle school",
  "high school",
]);

/**
 * GradeSchema
 * This model represents a grade in the system. It inherits from BaseModel.
 */
export const zGradeSchema = z.object({
  id: z.uuid(),
  yearId: z.uuid(),
  grade: zGradeEnum,
  level: zGradeLevelEnum,
  hasStream: z.boolean(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

/**
 * StudentApplicationStatusEnum
 */
export const zStudentApplicationStatusEnum = z.enum([
  "pending",
  "under-review",
  "documents-required",
  "approved",
  "rejected",
  "enrolled",
]);

/**
 * StudentSchema
 * This model represents a student in the system. It inherits from BaseModel.
 */
export const zStudentSchema = z.object({
  id: z.uuid(),
  firstName: z.string(),
  fatherName: z.string(),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  address: z.string(),
  city: z.string(),
  state: z.string(),
  postalCode: z.string(),
  fatherPhone: z.string(),
  motherPhone: z.string(),
  parentEmail: z.email(),
  grandFatherName: z.union([z.string(), z.null()]),
  nationality: z.union([z.string(), z.null()]),
  bloodType: z.optional(zBloodTypeEnum),
  studentPhoto: z.union([z.string(), z.null()]),
  previousSchool: z.union([z.string(), z.null()]),
  previousGrades: z.union([z.string(), z.null()]),
  transportation: z.union([z.string(), z.null()]),
  guardianName: z.union([z.string(), z.null()]),
  guardianPhone: z.union([z.string(), z.null()]),
  guardianRelation: z.union([z.string(), z.null()]),
  emergencyContactName: z.union([z.string(), z.null()]),
  emergencyContactPhone: z.union([z.string(), z.null()]),
  disabilityDetails: z.union([z.string(), z.null()]),
  siblingDetails: z.union([z.string(), z.null()]),
  medicalDetails: z.union([z.string(), z.null()]),
  siblingInSchool: z.boolean(),
  hasMedicalCondition: z.boolean(),
  hasDisability: z.boolean(),
  isTransfer: z.boolean(),
  status: z.optional(zStudentApplicationStatusEnum),
  userId: z.union([z.uuid(), z.null()]),
});

/**
 * HighestDegreeEnum
 */
export const zHighestDegreeEnum = z.enum(["bachelors", "masters", "doctorate"]);

/**
 * ScheduleEnum
 */
export const zScheduleEnum = z.enum([
  "full-time",
  "part-time",
  "flexible-hours",
  "substitute",
]);

/**
 * MaritalStatusEnum
 */
export const zMaritalStatusEnum = z.enum([
  "single",
  "married",
  "divorced",
  "widowed",
  "prefer-not-to-say",
]);

/**
 * TeacherApplicationStatus
 */
export const zTeacherApplicationStatus = z.enum([
  "pending",
  "approved",
  "rejected",
  "interview-scheduled",
  "under-review",
]);

/**
 * TeacherSchema
 */
export const zTeacherSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  firstName: z.string(),
  fatherName: z.string(),
  grandFatherName: z.string(),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  nationality: z.string(),
  socialSecurityNumber: z.string(),
  address: z.string(),
  city: z.string(),
  state: z.string(),
  postalCode: z.string(),
  country: z.string(),
  primaryPhone: z.string(),
  personalEmail: z.string(),
  emergencyContactName: z.string(),
  emergencyContactRelation: z.string(),
  emergencyContactPhone: z.string(),
  emergencyContactEmail: z.string(),
  highestDegree: zHighestDegreeEnum,
  university: z.string(),
  graduationYear: z.int(),
  gpa: z.number(),
  positionApplyingFor: z.string(),
  yearsOfExperience: zExperienceYearEnum,
  preferredSchedule: zScheduleEnum,
  reference1Name: z.string(),
  reference1Title: z.string(),
  reference1Organization: z.string(),
  reference1Phone: z.string(),
  reference1Email: z.string(),
  maritalStatus: z.optional(z.union([zMaritalStatusEnum, z.null()])),
  secondaryPhone: z.optional(z.union([z.string(), z.null()])),
  additionalDegrees: z.optional(z.union([z.string(), z.null()])),
  teachingLicense: z.optional(z.union([z.boolean(), z.null()])),
  licenseNumber: z.optional(z.union([z.string(), z.null()])),
  licenseState: z.optional(z.union([z.string(), z.null()])),
  licenseExpirationDate: z.optional(z.union([z.iso.date(), z.null()])),
  certifications: z.optional(z.union([z.string(), z.null()])),
  specializations: z.optional(z.union([z.string(), z.null()])),
  previousSchools: z.optional(z.union([z.string(), z.null()])),
  specialSkills: z.optional(z.union([z.string(), z.null()])),
  professionalDevelopment: z.optional(z.union([z.string(), z.null()])),
  hasConvictions: z.optional(z.boolean()).default(false),
  convictionDetails: z.optional(z.union([z.string(), z.null()])),
  hasDisciplinaryActions: z.optional(z.boolean()).default(false),
  disciplinaryDetails: z.optional(z.union([z.string(), z.null()])),
  reference2Name: z.optional(z.union([z.string(), z.null()])),
  reference2Title: z.optional(z.union([z.string(), z.null()])),
  reference2Organization: z.optional(z.union([z.string(), z.null()])),
  reference2Phone: z.optional(z.union([z.string(), z.null()])),
  reference2Email: z.optional(z.union([z.string(), z.null()])),
  reference3Name: z.optional(z.union([z.string(), z.null()])),
  reference3Title: z.optional(z.union([z.string(), z.null()])),
  reference3Organization: z.optional(z.union([z.string(), z.null()])),
  reference3Phone: z.optional(z.union([z.string(), z.null()])),
  reference3Email: z.optional(z.union([z.string(), z.null()])),
  resume: z.optional(z.union([z.string(), z.null()])),
  coverLetter: z.optional(z.union([z.string(), z.null()])),
  transcripts: z.optional(z.union([z.string(), z.null()])),
  teachingCertificate: z.optional(z.union([z.string(), z.null()])),
  backgroundCheck: z.optional(z.union([z.string(), z.null()])),
  teachingPhilosophy: z.optional(z.union([z.string(), z.null()])),
  whyTeaching: z.optional(z.union([z.string(), z.null()])),
  additionalComments: z.optional(z.union([z.string(), z.null()])),
  agreeToTerms: z.optional(z.boolean()).default(false),
  agreeToBackgroundCheck: z.optional(z.boolean()).default(false),
  userId: z.optional(z.union([z.uuid(), z.null()])),
  status: z.optional(zTeacherApplicationStatus),
});

/**
 * SubjectSchema
 * This model represents a subject in the system. It inherits from BaseModel.
 */
export const zSubjectSchema = z.object({
  id: z.uuid(),
  yearId: z.uuid(),
  name: z.string(),
  code: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

/**
 * YearWithRelatedSchema
 * This model represents a YearSchema with its relationships.
 */
export const zYearWithRelatedSchema = z.object({
  events: z.array(zEventSchema),
  academicTerms: z.array(zAcademicTermSchema),
  grades: z.array(zGradeSchema),
  students: z.array(zStudentSchema),
  teachers: z.array(zTeacherSchema),
  subjects: z.array(zSubjectSchema),
  id: z.uuid(),
  calendarType: zAcademicTermTypeEnum,
  name: z.string(),
  startDate: z.iso.date(),
  endDate: z.iso.date(),
  status: zAcademicYearStatusEnum,
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

/**
 * SectionSchema
 * This model represents a section in the system.
 */
export const zSectionSchema = z.object({
  id: z.uuid(),
  gradeId: z.uuid(),
  section: z.string(),
});

/**
 * StreamSchema
 * This model represents a stream in the system.
 */
export const zStreamSchema = z.object({
  id: z.uuid(),
  gradeId: z.uuid(),
  name: z.string(),
});

/**
 * TeacherTermRecordWithRelatedSchema
 * This model combines the TeacherTermRecordSchema with its relationships.
 * It is used to provide a complete view of a teacher's term record along with related entities.
 */
export const zTeacherTermRecordWithRelatedSchema = z.object({
  teacher: z.optional(z.union([zTeacherSchema, z.null()])),
  academicTerm: z.optional(z.union([zAcademicTermSchema, z.null()])),
  subject: z.optional(z.union([zSubjectSchema, z.null()])),
  section: z.optional(z.union([zSectionSchema, z.null()])),
  grade: z.optional(z.union([zGradeSchema, z.null()])),
  stream: z.optional(z.union([zStreamSchema, z.null()])),
  id: z.uuid(),
  teacherId: z.uuid(),
  academicTermId: z.uuid(),
  subjectId: z.uuid(),
  gradeId: z.uuid(),
  sectionId: z.uuid(),
  streamId: z.union([z.uuid(), z.null()]),
});

/**
 * MarkListTypeEnum
 */
export const zMarkListTypeEnum = z.enum([
  "Test",
  "Quiz",
  "Assignment",
  "Midterm",
  "Final",
]);

/**
 * MarkListSchema
 * This model represents an assessment record for a student including details
 */
export const zMarkListSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  studentId: z.uuid(),
  studentTermRecordId: z.uuid(),
  subjectId: z.uuid(),
  type: zMarkListTypeEnum,
  percentage: z.optional(z.union([z.number(), z.null()])),
  score: z.optional(z.union([z.number(), z.null()])),
});

/**
 * StudentTermRecordWithRelatedSchema
 * This model combines the StudentTermRecordSchema with its relationships.
 * It is used to provide a complete view of a student's term record along with related entities.
 */
export const zStudentTermRecordWithRelatedSchema = z.object({
  student: z.optional(z.union([zStudentSchema, z.null()])),
  academicTerm: z.optional(z.union([zAcademicTermSchema, z.null()])),
  grade: z.optional(z.union([zGradeSchema, z.null()])),
  section: z.optional(z.union([zSectionSchema, z.null()])),
  stream: z.optional(z.union([zStreamSchema, z.null()])),
  markLists: z.union([z.array(zMarkListSchema), z.null()]),
  id: z.optional(z.union([z.uuid(), z.null()])),
  studentId: z.uuid(),
  academicTermId: z.uuid(),
  gradeId: z.uuid(),
  sectionId: z.uuid(),
  streamId: z.optional(z.union([z.uuid(), z.null()])),
  average: z.optional(z.union([z.number(), z.null()])),
  rank: z.optional(z.union([z.int(), z.null()])),
});

/**
 * UserSchema
 */
export const zUserSchema = z.object({
  id: z.uuid(),
  identification: z.string(),
  role: zRoleEnum,
  imagePath: z.optional(z.union([z.string(), z.null()])),
  createdAt: z.iso.datetime(),
});

/**
 * YearSchema
 * This model represents a year in the system.
 */
export const zYearSchema = z.object({
  id: z.uuid(),
  calendarType: zAcademicTermTypeEnum,
  name: z.string(),
  startDate: z.iso.date(),
  endDate: z.iso.date(),
  status: zAcademicYearStatusEnum,
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

/**
 * TeacherTermRecordSchema
 */
export const zTeacherTermRecordSchema = z.object({
  id: z.uuid(),
  teacherId: z.uuid(),
  academicTermId: z.uuid(),
  subjectId: z.uuid(),
  gradeId: z.uuid(),
  sectionId: z.uuid(),
  streamId: z.union([z.uuid(), z.null()]),
});

/**
 * TeacherWithRelatedSchema
 * This model extends TeacherSchema to include relationships.
 */
export const zTeacherWithRelatedSchemaOutput = z.object({
  user: z.optional(z.union([zUserSchema, z.null()])),
  sections: z.optional(z.union([z.array(zSectionSchema), z.null()])),
  years: z.optional(z.union([z.array(zYearSchema), z.null()])),
  termRecords: z.optional(
    z.union([z.array(zTeacherTermRecordSchema), z.null()]),
  ),
  academicTerms: z.optional(z.union([z.array(zAcademicTermSchema), z.null()])),
  grades: z.optional(z.union([z.array(zGradeSchema), z.null()])),
  subjects: z.optional(z.union([z.array(zSubjectSchema), z.null()])),
  id: z.optional(z.union([z.uuid(), z.null()])),
  firstName: z.string(),
  fatherName: z.string(),
  grandFatherName: z.string(),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  nationality: z.string(),
  socialSecurityNumber: z.string(),
  address: z.string(),
  city: z.string(),
  state: z.string(),
  postalCode: z.string(),
  country: z.string(),
  primaryPhone: z.string(),
  personalEmail: z.string(),
  emergencyContactName: z.string(),
  emergencyContactRelation: z.string(),
  emergencyContactPhone: z.string(),
  emergencyContactEmail: z.string(),
  highestDegree: zHighestDegreeEnum,
  university: z.string(),
  graduationYear: z.int(),
  gpa: z.number(),
  positionApplyingFor: z.string(),
  yearsOfExperience: zExperienceYearEnum,
  preferredSchedule: zScheduleEnum,
  reference1Name: z.string(),
  reference1Title: z.string(),
  reference1Organization: z.string(),
  reference1Phone: z.string(),
  reference1Email: z.string(),
  maritalStatus: z.optional(z.union([zMaritalStatusEnum, z.null()])),
  secondaryPhone: z.optional(z.union([z.string(), z.null()])),
  additionalDegrees: z.optional(z.union([z.string(), z.null()])),
  teachingLicense: z.optional(z.union([z.boolean(), z.null()])),
  licenseNumber: z.optional(z.union([z.string(), z.null()])),
  licenseState: z.optional(z.union([z.string(), z.null()])),
  licenseExpirationDate: z.optional(z.union([z.iso.date(), z.null()])),
  certifications: z.optional(z.union([z.string(), z.null()])),
  specializations: z.optional(z.union([z.string(), z.null()])),
  previousSchools: z.optional(z.union([z.string(), z.null()])),
  specialSkills: z.optional(z.union([z.string(), z.null()])),
  professionalDevelopment: z.optional(z.union([z.string(), z.null()])),
  hasConvictions: z.optional(z.boolean()).default(false),
  convictionDetails: z.optional(z.union([z.string(), z.null()])),
  hasDisciplinaryActions: z.optional(z.boolean()).default(false),
  disciplinaryDetails: z.optional(z.union([z.string(), z.null()])),
  reference2Name: z.optional(z.union([z.string(), z.null()])),
  reference2Title: z.optional(z.union([z.string(), z.null()])),
  reference2Organization: z.optional(z.union([z.string(), z.null()])),
  reference2Phone: z.optional(z.union([z.string(), z.null()])),
  reference2Email: z.optional(z.union([z.string(), z.null()])),
  reference3Name: z.optional(z.union([z.string(), z.null()])),
  reference3Title: z.optional(z.union([z.string(), z.null()])),
  reference3Organization: z.optional(z.union([z.string(), z.null()])),
  reference3Phone: z.optional(z.union([z.string(), z.null()])),
  reference3Email: z.optional(z.union([z.string(), z.null()])),
  resume: z.optional(z.union([z.string(), z.null()])),
  coverLetter: z.optional(z.union([z.string(), z.null()])),
  transcripts: z.optional(z.union([z.string(), z.null()])),
  teachingCertificate: z.optional(z.union([z.string(), z.null()])),
  backgroundCheck: z.optional(z.union([z.string(), z.null()])),
  teachingPhilosophy: z.optional(z.union([z.string(), z.null()])),
  whyTeaching: z.optional(z.union([z.string(), z.null()])),
  additionalComments: z.optional(z.union([z.string(), z.null()])),
  agreeToTerms: z.optional(z.boolean()).default(false),
  agreeToBackgroundCheck: z.optional(z.boolean()).default(false),
  userId: z.optional(z.union([z.uuid(), z.null()])),
  status: z.optional(zTeacherApplicationStatus),
});

/**
 * StudentTermRecordSchema
 * This model represents the average result of a student for a particular term and year.
 */
export const zStudentTermRecordSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  studentId: z.uuid(),
  academicTermId: z.uuid(),
  gradeId: z.uuid(),
  sectionId: z.uuid(),
  streamId: z.optional(z.union([z.uuid(), z.null()])),
  average: z.optional(z.union([z.number(), z.null()])),
  rank: z.optional(z.union([z.int(), z.null()])),
});

/**
 * StudentYearRecordSchema
 * This model represents a student's yearly academic record.
 */
export const zStudentYearRecordSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  studentId: z.uuid(),
  gradeId: z.uuid(),
  yearId: z.uuid(),
  streamId: z.optional(z.union([z.uuid(), z.null()])),
  finalScore: z.optional(z.union([z.number(), z.null()])),
  rank: z.optional(z.union([z.int(), z.null()])),
});

/**
 * StreamWithRelatedSchema
 */
export const zStreamWithRelatedSchema = z.object({
  teacherTermRecords: z.optional(
    z.union([z.array(zTeacherTermRecordSchema), z.null()]),
  ),
  studentTermRecords: z.optional(
    z.union([z.array(zStudentTermRecordSchema), z.null()]),
  ),
  grade: z.optional(z.union([zGradeSchema, z.null()])),
  students: z.optional(z.union([z.array(zStudentYearRecordSchema), z.null()])),
  subjects: z.optional(z.union([z.array(zSubjectSchema), z.null()])),
  id: z.uuid(),
  gradeId: z.uuid(),
  name: z.string(),
});

/**
 * SubjectYearlyAverageSchema
 * This model represents the yearly average of a subject for a student.
 */
export const zSubjectYearlyAverageSchema = z.object({
  id: z.optional(z.union([z.uuid(), z.null()])),
  studentId: z.uuid(),
  yearlySubjectId: z.uuid(),
  studentYearRecordId: z.optional(z.union([z.uuid(), z.null()])),
  average: z.optional(z.union([z.number(), z.null()])),
  rank: z.optional(z.union([z.int(), z.null()])),
});

/**
 * StudentWithRelatedSchema
 */
export const zStudentWithRelatedSchema = z.object({
  startingGrade: z.union([zGradeSchema, z.null()]),
  user: z.union([zUserSchema, z.null()]),
  termRecords: z.array(zStudentTermRecordSchema),
  studentYearRecords: z.array(zStudentYearRecordSchema),
  subjectYearlyAverages: z.array(zSubjectYearlyAverageSchema),
  assessments: z.array(zAssessmentSchema),
  years: z.array(zYearSchema),
  academicTerms: z.array(zAcademicTermSchema),
  grades: z.array(zGradeSchema),
  subjects: z.array(zSubjectSchema),
  sections: z.array(zSectionSchema),
  markLists: z.array(zMarkListSchema),
  id: z.uuid(),
  firstName: z.string(),
  fatherName: z.string(),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  address: z.string(),
  city: z.string(),
  state: z.string(),
  postalCode: z.string(),
  fatherPhone: z.string(),
  motherPhone: z.string(),
  parentEmail: z.email(),
  grandFatherName: z.union([z.string(), z.null()]),
  nationality: z.union([z.string(), z.null()]),
  bloodType: z.optional(zBloodTypeEnum),
  studentPhoto: z.union([z.string(), z.null()]),
  previousSchool: z.union([z.string(), z.null()]),
  previousGrades: z.union([z.string(), z.null()]),
  transportation: z.union([z.string(), z.null()]),
  guardianName: z.union([z.string(), z.null()]),
  guardianPhone: z.union([z.string(), z.null()]),
  guardianRelation: z.union([z.string(), z.null()]),
  emergencyContactName: z.union([z.string(), z.null()]),
  emergencyContactPhone: z.union([z.string(), z.null()]),
  disabilityDetails: z.union([z.string(), z.null()]),
  siblingDetails: z.union([z.string(), z.null()]),
  medicalDetails: z.union([z.string(), z.null()]),
  siblingInSchool: z.boolean(),
  hasMedicalCondition: z.boolean(),
  hasDisability: z.boolean(),
  isTransfer: z.boolean(),
  status: z.optional(zStudentApplicationStatusEnum),
  userId: z.union([z.uuid(), z.null()]),
});

/**
 * SectionWithRelatedSchema
 * This model represents a SectionSchema with its relationships.
 */
export const zSectionWithRelatedSchema = z.object({
  teacherTermRecords: z.optional(
    z.union([z.array(zTeacherTermRecordSchema), z.null()]),
  ),
  studentTermRecords: z.optional(
    z.union([z.array(zStudentTermRecordSchema), z.null()]),
  ),
  grade: z.optional(z.union([zGradeSchema, z.null()])),
  students: z.optional(z.union([z.array(zStudentSchema), z.null()])),
  teachers: z.optional(z.union([z.array(zTeacherSchema), z.null()])),
  id: z.uuid(),
  gradeId: z.uuid(),
  section: z.string(),
});

/**
 * SubjectWithRelatedSchema
 */
export const zSubjectWithRelatedSchema = z.object({
  year: zYearSchema,
  teacherTermRecords: z.union([z.array(zTeacherTermRecordSchema), z.null()]),
  teachers: z.array(zTeacherSchema),
  students: z.array(zStudentSchema),
  markLists: z.array(zMarkListSchema),
  streams: z.array(zStreamSchema),
  grades: z.array(zGradeSchema),
  id: z.uuid(),
  yearId: z.uuid(),
  name: z.string(),
  code: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

/**
 * GradeNestedSchema
 * This model represents the relationships of a GradeSchema.
 * It is used to define the relationships between the GradeSchema and other schemas.
 */
export const zGradeNestedSchema = z.object({
  id: z.uuid(),
  yearId: z.uuid(),
  grade: zGradeEnum,
  level: zGradeLevelEnum,
  hasStream: z.boolean(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  year: zYearWithRelatedSchema,
  teacherTermRecords: z.array(zTeacherTermRecordWithRelatedSchema),
  studentTermRecords: z.array(zStudentTermRecordWithRelatedSchema),
  teachers: z.array(zTeacherWithRelatedSchemaOutput),
  streams: z.array(zStreamWithRelatedSchema),
  students: z.array(zStudentWithRelatedSchema),
  sections: z.array(zSectionWithRelatedSchema),
  subjects: z.array(zSubjectWithRelatedSchema),
});

/**
 * StreamSetupSchema
 */
export const zStreamSetupSchema = z.object({
  id: z.uuid(),
  gradeId: z.uuid(),
  name: z.string(),
  subjects: z.array(zSubjectSchema),
});

/**
 * GradeSetupSchema
 */
export const zGradeSetupSchema = z.object({
  id: z.uuid(),
  yearId: z.uuid(),
  grade: zGradeEnum,
  level: zGradeLevelEnum,
  hasStream: z.boolean(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  subjects: z.array(zSubjectSchema),
  streams: z.array(zStreamSetupSchema),
  sections: z.array(zSectionSchema),
});

/**
 * GradeWithRelatedSchema
 */
export const zGradeWithRelatedSchema = z.object({
  year: z.union([zYearSchema, z.null()]),
  teacherTermRecords: z.array(zTeacherTermRecordSchema),
  studentTermRecords: z.array(zStudentTermRecordSchema),
  teachers: z.array(zTeacherSchema),
  streams: z.array(zStreamSchema),
  students: z.array(zStudentSchema),
  sections: z.array(zSectionSchema),
  subjects: z.array(zSubjectSchema),
  id: z.uuid(),
  yearId: z.uuid(),
  grade: zGradeEnum,
  level: zGradeLevelEnum,
  hasStream: z.boolean(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

/**
 * LogOutResponse
 */
export const zLogOutResponse = z.object({
  message: z.string(),
});

/**
 * NewGrade
 */
export const zNewGrade = z.object({
  grade: zGradeEnum,
  level: zGradeLevelEnum,
  hasStream: z.boolean(),
  yearId: z.uuid(),
});

/**
 * NewGradeSuccess
 */
export const zNewGradeSuccess = z.object({
  id: z.uuid(),
  message: z.optional(z.string()).default("Grade created Successfully"),
});

/**
 * NewSubject
 */
export const zNewSubject = z.object({
  name: z.string().min(3).max(50),
  code: z.string().min(3).max(10),
  yearId: z.uuid(),
});

/**
 * NewSubjectSuccess
 */
export const zNewSubjectSuccess = z.object({
  id: z.uuid(),
  message: z.optional(z.string()).default("Subject created Successfully"),
});

/**
 * NewYear
 * This model represents a new year to be created in the system.
 */
export const zNewYear = z.object({
  name: z.string(),
  calendarType: zAcademicTermTypeEnum,
  status: zAcademicYearStatusEnum,
  startDate: z.iso.date(),
  endDate: z.iso.date(),
  setupMethods: z.enum(["Default Template", "Manual", "Last Year Copy"]),
  copyFromYearId: z.optional(z.union([z.uuid(), z.null()])),
});

/**
 * NewYearSuccess
 */
export const zNewYearSuccess = z.object({
  id: z.uuid(),
  message: z.optional(z.string()).default("Year created Successfully"),
});

/**
 * RegistrationResponse
 * Schema for successful registration response.
 */
export const zRegistrationResponse = z.object({
  id: z.uuid(),
  message: z.string(),
});

/**
 * RegistrationStep
 */
export const zRegistrationStep = z.object({
  message: z.string(),
});

/**
 * StudRegStep1
 */
export const zStudRegStep1 = z.object({
  firstName: z.string().min(3).max(50),
  fatherName: z.string().min(3).max(50),
  grandFatherName: z.optional(z.union([z.string(), z.null()])),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  nationality: z.optional(z.union([z.string().min(3).max(100), z.null()])),
});

/**
 * StudRegStep2
 */
export const zStudRegStep2 = z.object({
  registeredForGradeId: z.uuid(),
  transportation: z.optional(z.union([z.string(), z.null()])),
  isTransfer: z.optional(z.boolean()).default(false),
  previousSchool: z.optional(z.union([z.string().max(100), z.null()])),
});

/**
 * StudRegStep3
 */
export const zStudRegStep3 = z.object({
  address: z.string(),
  city: z.string().min(3).max(50),
  state: z.string().min(3).max(50),
  postalCode: z.string().min(3).max(20),
  fatherPhone: z.string(),
  motherPhone: z.string(),
  parentEmail: z.email(),
});

/**
 * StudRegStep4
 */
export const zStudRegStep4 = z.object({
  guardianName: z.optional(z.union([z.string(), z.null()])),
  guardianPhone: z.optional(z.union([z.string(), z.null()])),
  guardianRelation: z.optional(z.union([z.string(), z.null()])),
  emergencyContactName: z.optional(z.union([z.string(), z.null()])),
  emergencyContactPhone: z.union([z.string(), z.null()]),
  siblingInSchool: z.optional(z.boolean()).default(false),
  siblingDetails: z.optional(z.union([z.string(), z.null()])),
});

/**
 * StudRegStep5
 */
export const zStudRegStep5 = z.object({
  bloodType: z.optional(zBloodTypeEnum),
  studentPhoto: z.optional(z.union([z.string(), z.null()])),
  hasMedicalCondition: z.optional(z.boolean()).default(false),
  medicalDetails: z.optional(z.union([z.string(), z.null()])),
  hasDisability: z.optional(z.boolean()).default(false),
  disabilityDetails: z.optional(z.union([z.string(), z.null()])),
});

/**
 * StudentCurrentGrade
 */
export const zStudentCurrentGrade = z.object({
  id: z.uuid(),
  grade: zGradeEnum,
});

/**
 * StudentBasicInfo
 */
export const zStudentBasicInfo = z.object({
  id: z.uuid(),
  firstName: z.string(),
  fatherName: z.string(),
  grandFatherName: z.union([z.string(), z.null()]),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  address: z.string(),
  city: z.string(),
  state: z.string(),
  postalCode: z.string(),
  fatherPhone: z.string(),
  motherPhone: z.string(),
  parentEmail: z.email(),
  bloodType: z.optional(zBloodTypeEnum),
  previousSchool: z.union([z.string(), z.null()]),
  guardianName: z.union([z.string(), z.null()]),
  guardianPhone: z.union([z.string(), z.null()]),
  guardianRelation: z.union([z.string(), z.null()]),
  siblingInSchool: z.boolean(),
  hasMedicalCondition: z.boolean(),
  hasDisability: z.boolean(),
  isTransfer: z.boolean(),
  status: zStudentApplicationStatusEnum,
  grade: zStudentCurrentGrade,
  createdAt: z.iso.datetime(),
});

/**
 * StudentInfo
 */
export const zStudentInfo = z.object({
  id: z.uuid(),
  identification: z.string(),
  role: zRoleEnum,
  imagePath: z.optional(z.union([z.string(), z.null()])),
  createdAt: z.iso.datetime(),
  student: zStudentSchema,
});

/**
 * StudentRegistrationForm
 */
export const zStudentRegistrationForm = z.object({
  bloodType: z.optional(zBloodTypeEnum),
  studentPhoto: z.optional(z.union([z.string(), z.null()])),
  hasMedicalCondition: z.optional(z.boolean()).default(false),
  medicalDetails: z.optional(z.union([z.string(), z.null()])),
  hasDisability: z.optional(z.boolean()).default(false),
  disabilityDetails: z.optional(z.union([z.string(), z.null()])),
  guardianName: z.optional(z.union([z.string(), z.null()])),
  guardianPhone: z.optional(z.union([z.string(), z.null()])),
  guardianRelation: z.optional(z.union([z.string(), z.null()])),
  emergencyContactName: z.optional(z.union([z.string(), z.null()])),
  emergencyContactPhone: z.union([z.string(), z.null()]),
  siblingInSchool: z.optional(z.boolean()).default(false),
  siblingDetails: z.optional(z.union([z.string(), z.null()])),
  address: z.string(),
  city: z.string().min(3).max(50),
  state: z.string().min(3).max(50),
  postalCode: z.string().min(3).max(20),
  fatherPhone: z.string(),
  motherPhone: z.string(),
  parentEmail: z.email(),
  registeredForGradeId: z.uuid(),
  transportation: z.optional(z.union([z.string(), z.null()])),
  isTransfer: z.optional(z.boolean()).default(false),
  previousSchool: z.optional(z.union([z.string().max(100), z.null()])),
  firstName: z.string().min(3).max(50),
  fatherName: z.string().min(3).max(50),
  grandFatherName: z.optional(z.union([z.string(), z.null()])),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  nationality: z.optional(z.union([z.string().min(3).max(100), z.null()])),
  status: z.optional(zStudentApplicationStatusEnum),
});

/**
 * SubjectNestedSchema
 * This model represents the relationships of a SubjectSchema.
 * It is used to define the relationships between the SubjectSchema and other schemas.
 */
export const zSubjectNestedSchema = z.object({
  id: z.uuid(),
  yearId: z.uuid(),
  name: z.string(),
  code: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  teacherTermRecords: z.array(zTeacherTermRecordWithRelatedSchema),
  teachers: z.array(zTeacherWithRelatedSchemaOutput),
  streams: z.array(zStreamWithRelatedSchema),
  grades: z.array(zGradeWithRelatedSchema),
});

/**
 * SubjectSetupSchema
 */
export const zSubjectSetupSchema = z.object({
  id: z.uuid(),
  yearId: z.uuid(),
  name: z.string(),
  code: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
  grades: z.array(zGradeSchema),
  streams: z.array(zStreamSchema),
});

/**
 * SuccessResponseSchema[RegistrationResponse, NoneType, NoneType]
 */
export const zSuccessResponseSchemaRegistrationResponseNoneTypeNoneType =
  z.object({
    data: zRegistrationResponse,
    message: z.optional(z.string()).default("Success"),
    meta: z.optional(z.null()),
    links: z.optional(z.null()),
  });

/**
 * TeacherInfo
 */
export const zTeacherInfo = z.object({
  id: z.uuid(),
  identification: z.string(),
  role: zRoleEnum,
  imagePath: z.optional(z.union([z.string(), z.null()])),
  createdAt: z.iso.datetime(),
  teacher: zTeacherSchema,
});

/**
 * TeacherWithRelatedSchema
 * This model extends TeacherSchema to include relationships.
 */
export const zTeacherWithRelatedSchemaInput = z.object({
  user: z.optional(z.union([zUserSchema, z.null()])),
  sections: z.optional(z.union([z.array(zSectionSchema), z.null()])),
  years: z.optional(z.union([z.array(zYearSchema), z.null()])),
  termRecords: z.optional(
    z.union([z.array(zTeacherTermRecordSchema), z.null()]),
  ),
  academicTerms: z.optional(z.union([z.array(zAcademicTermSchema), z.null()])),
  grades: z.optional(z.union([z.array(zGradeSchema), z.null()])),
  subjects: z.optional(z.union([z.array(zSubjectSchema), z.null()])),
  id: z.optional(z.union([z.uuid(), z.null()])),
  firstName: z.string(),
  fatherName: z.string(),
  grandFatherName: z.string(),
  dateOfBirth: z.iso.date(),
  gender: zGenderEnum,
  nationality: z.string(),
  socialSecurityNumber: z.string(),
  address: z.string(),
  city: z.string(),
  state: z.string(),
  postalCode: z.string(),
  country: z.string(),
  primaryPhone: z.string(),
  personalEmail: z.string(),
  emergencyContactName: z.string(),
  emergencyContactRelation: z.string(),
  emergencyContactPhone: z.string(),
  emergencyContactEmail: z.string(),
  highestDegree: zHighestDegreeEnum,
  university: z.string(),
  graduationYear: z.int(),
  gpa: z.number(),
  positionApplyingFor: z.string(),
  yearsOfExperience: zExperienceYearEnum,
  preferredSchedule: zScheduleEnum,
  reference1Name: z.string(),
  reference1Title: z.string(),
  reference1Organization: z.string(),
  reference1Phone: z.string(),
  reference1Email: z.string(),
  maritalStatus: z.optional(z.union([zMaritalStatusEnum, z.null()])),
  secondaryPhone: z.optional(z.union([z.string(), z.null()])),
  additionalDegrees: z.optional(z.union([z.string(), z.null()])),
  teachingLicense: z.optional(z.union([z.boolean(), z.null()])),
  licenseNumber: z.optional(z.union([z.string(), z.null()])),
  licenseState: z.optional(z.union([z.string(), z.null()])),
  licenseExpirationDate: z.optional(z.union([z.iso.date(), z.null()])),
  certifications: z.optional(z.union([z.string(), z.null()])),
  specializations: z.optional(z.union([z.string(), z.null()])),
  previousSchools: z.optional(z.union([z.string(), z.null()])),
  specialSkills: z.optional(z.union([z.string(), z.null()])),
  professionalDevelopment: z.optional(z.union([z.string(), z.null()])),
  hasConvictions: z.optional(z.boolean()).default(false),
  convictionDetails: z.optional(z.union([z.string(), z.null()])),
  hasDisciplinaryActions: z.optional(z.boolean()).default(false),
  disciplinaryDetails: z.optional(z.union([z.string(), z.null()])),
  reference2Name: z.optional(z.union([z.string(), z.null()])),
  reference2Title: z.optional(z.union([z.string(), z.null()])),
  reference2Organization: z.optional(z.union([z.string(), z.null()])),
  reference2Phone: z.optional(z.union([z.string(), z.null()])),
  reference2Email: z.optional(z.union([z.string(), z.null()])),
  reference3Name: z.optional(z.union([z.string(), z.null()])),
  reference3Title: z.optional(z.union([z.string(), z.null()])),
  reference3Organization: z.optional(z.union([z.string(), z.null()])),
  reference3Phone: z.optional(z.union([z.string(), z.null()])),
  reference3Email: z.optional(z.union([z.string(), z.null()])),
  resume: z.optional(z.union([z.string(), z.null()])),
  coverLetter: z.optional(z.union([z.string(), z.null()])),
  transcripts: z.optional(z.union([z.string(), z.null()])),
  teachingCertificate: z.optional(z.union([z.string(), z.null()])),
  backgroundCheck: z.optional(z.union([z.string(), z.null()])),
  teachingPhilosophy: z.optional(z.union([z.string(), z.null()])),
  whyTeaching: z.optional(z.union([z.string(), z.null()])),
  additionalComments: z.optional(z.union([z.string(), z.null()])),
  agreeToTerms: z.optional(z.boolean()).default(false),
  agreeToBackgroundCheck: z.optional(z.boolean()).default(false),
  userId: z.optional(z.union([z.uuid(), z.null()])),
  status: z.optional(zTeacherApplicationStatus),
});

/**
 * Token
 */
export const zToken = z.object({
  access_token: z.string(),
  token_type: z.string(),
});

/**
 * UpdateSubject
 * This model represents a subject that can be updated in the system.
 */
export const zUpdateSubject = z.object({
  id: z.uuid(),
  name: z.string(),
  code: z.string(),
});

/**
 * UpdateStreamSetup
 */
export const zUpdateStreamSetup = z.object({
  id: z.uuid(),
  name: z.optional(z.union([z.string(), z.null()])),
  subjects: z.array(zUpdateSubject),
});

/**
 * UpdateSection
 * This model represents a section in the system that can be updated.
 */
export const zUpdateSection = z.object({
  id: z.uuid(),
  section: z.string(),
});

/**
 * UpdateGradeSetup
 * Update Grade Setup Schema
 */
export const zUpdateGradeSetup = z.object({
  grade: z.optional(z.union([zGradeEnum, z.null()])),
  level: z.optional(z.union([zGradeLevelEnum, z.null()])),
  hasStream: z.optional(z.union([z.boolean(), z.null()])),
  subjects: z.optional(z.union([z.array(zUpdateSubject), z.null()])),
  streams: z.optional(z.union([z.array(zUpdateStreamSetup), z.null()])),
  sections: z.optional(z.union([z.array(zUpdateSection), z.null()])),
});

/**
 * UpdateGradeSetupSuccess
 */
export const zUpdateGradeSetupSuccess = z.object({
  message: z.optional(z.string()).default("Grade Setup updated Successfully"),
});

/**
 * UpdateSubjectGrade
 */
export const zUpdateSubjectGrade = z.object({
  id: z.uuid(),
});

/**
 * UpdateSubjectStream
 */
export const zUpdateSubjectStream = z.object({
  id: z.uuid(),
  gradeId: z.uuid(),
});

/**
 * UpdateSubjectSetup
 */
export const zUpdateSubjectSetup = z.object({
  name: z.optional(z.union([z.string().min(3).max(50), z.null()])),
  code: z.optional(z.union([z.string().min(3).max(10), z.null()])),
  grades: z.optional(z.union([z.array(zUpdateSubjectGrade), z.null()])),
  streams: z.optional(z.union([z.array(zUpdateSubjectStream), z.null()])),
});

/**
 * UpdateSubjectSetupSuccess
 */
export const zUpdateSubjectSetupSuccess = z.object({
  message: z.optional(z.string()).default("Subject Setup updated Successfully"),
});

/**
 * YearSummary
 */
export const zYearSummary = z.object({
  id: z.uuid(),
  calendarType: zAcademicTermTypeEnum,
  name: z.string(),
  startDate: z.iso.date(),
  endDate: z.iso.date(),
  status: zAcademicYearStatusEnum,
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export const zLoginData = z.object({
  body: zBodyLoginCredential,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zLoginResponse = zToken;

export const zLogoutData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zLogoutResponse = zLogOutResponse;

export const zRegisterNewAdminData = z.object({
  body: zAdminSchema,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterNewAdminResponse = zRegistrationResponse;

export const zRegisterStudentStep1Data = z.object({
  body: zStudRegStep1,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterStudentStep1Response = zRegistrationStep;

export const zRegisterStudentStep2Data = z.object({
  body: zStudRegStep2,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterStudentStep2Response = zRegistrationStep;

export const zRegisterStudentStep3Data = z.object({
  body: zStudRegStep3,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterStudentStep3Response = zRegistrationStep;

export const zRegisterStudentStep4Data = z.object({
  body: zStudRegStep4,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterStudentStep4Response = zRegistrationStep;

export const zRegisterStudentStep5Data = z.object({
  body: zStudRegStep5,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterStudentStep5Response = zRegistrationStep;

export const zRegisterNewStudentData = z.object({
  body: zStudentRegistrationForm,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterNewStudentResponse = zRegistrationResponse;

export const zRegisterNewTeacherData = z.object({
  body: zTeacherWithRelatedSchemaInput,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zRegisterNewTeacherResponse =
  zSuccessResponseSchemaRegistrationResponseNoneTypeNoneType;

export const zGetYearsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Response Get Years Api V1 Years  Get
 * Successful Response
 */
export const zGetYearsResponse = z.array(zYearSchema);

export const zPostYearData = z.object({
  body: zNewYear,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zPostYearResponse = zNewYearSuccess;

export const zGetYearSummaryData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      q: z.optional(z.union([z.string(), z.null()])),
    }),
  ),
});

/**
 * Response Get Year Summary Api V1 Years Summary Get
 * Successful Response
 */
export const zGetYearSummaryResponse = z.array(zYearSummary);

export const zDeleteYearData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    year_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zDeleteYearResponse = zDeleteYearSuccess;

export const zGetYearByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    year_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetYearByIdResponse = zYearSchema;

export const zGetDetailGradesByYearIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    year_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Get Detail Grades By Year Id Api V1 Years  Year Id  Grades Detail Get
 * Successful Response
 */
export const zGetDetailGradesByYearIdResponse = z.array(zGradeNestedSchema);

export const zGetDetailSubjectsByYearIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    year_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Response Get Detail Subjects By Year Id Api V1 Years  Year Id  Subjects Detail Get
 * Successful Response
 */
export const zGetDetailSubjectsByYearIdResponse = z.array(zSubjectNestedSchema);

export const zGetGradesData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    yearId: z.uuid(),
    q: z.optional(z.union([z.string(), z.null()])),
  }),
});

/**
 * Response Get Grades Api V1 Grades  Get
 * Successful Response
 */
export const zGetGradesResponse = z.array(zGradeSchema);

export const zPostGradeData = z.object({
  body: zNewGrade,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zPostGradeResponse = zNewGradeSuccess;

export const zGetGradesSetupData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    yearId: z.uuid(),
    q: z.optional(z.union([z.string(), z.null()])),
  }),
});

/**
 * Response Get Grades Setup Api V1 Grades Setup Get
 * Successful Response
 */
export const zGetGradesSetupResponse = z.array(zGradeSetupSchema);

export const zGetGradesSetupByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    grade_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetGradesSetupByIdResponse = zGradeSetupSchema;

export const zPatchGradeSetupData = z.object({
  body: zUpdateGradeSetup,
  path: z.object({
    grade_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zPatchGradeSetupResponse = zUpdateGradeSetupSuccess;

export const zGetGradeByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    grade_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetGradeByIdResponse = zGradeSchema;

export const zGetSubjectsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    yearId: z.uuid(),
    q: z.optional(z.union([z.string(), z.null()])),
  }),
});

/**
 * Response Get Subjects Api V1 Subjects  Get
 * Successful Response
 */
export const zGetSubjectsResponse = z.array(zSubjectSchema);

export const zPostSubjectData = z.object({
  body: zNewSubject,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zPostSubjectResponse = zNewSubjectSuccess;

export const zGetSubjectsSetupData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    yearId: z.uuid(),
    q: z.optional(z.union([z.string(), z.null()])),
  }),
});

/**
 * Response Get Subjects Setup Api V1 Subjects Setup Get
 * Successful Response
 */
export const zGetSubjectsSetupResponse = z.array(zSubjectSetupSchema);

export const zGetSubjectSetupByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    subject_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetSubjectSetupByIdResponse = zSubjectSetupSchema;

export const zPatchSubjectSetupData = z.object({
  body: zUpdateSubjectSetup,
  path: z.object({
    subject_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zPatchSubjectSetupResponse = zUpdateSubjectSetupSuccess;

export const zGetSubjectByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    subject_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetSubjectByIdResponse = zSubjectSchema;

export const zGetStreamsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    yearId: z.uuid(),
    q: z.optional(z.union([z.string(), z.null()])),
  }),
});

/**
 * Response Get Streams Api V1 Streams  Get
 * Successful Response
 */
export const zGetStreamsResponse = z.array(zStreamSchema);

export const zGetStreamByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    stream_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetStreamByIdResponse = zStreamSchema;

export const zGetSectionsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    gradeId: z.uuid(),
    q: z.optional(z.union([z.string(), z.null()])),
  }),
});

/**
 * Response Get Sections Api V1 Sections  Get
 * Successful Response
 */
export const zGetSectionsResponse = z.array(zSectionSchema);

export const zGetSectionByIdData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    section_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetSectionByIdResponse = zSectionSchema;

export const zGetLoggedInUserData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetLoggedInUserResponse = zUserSchema;

export const zGetAdminBasicInfoData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetAdminBasicInfoResponse = zAdminInfo;

export const zGetTeacherBasicInfoData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetTeacherBasicInfoResponse = zTeacherInfo;

export const zGetStudentBasicInfoData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetStudentBasicInfoResponse = zStudentInfo;

export const zGetStudentsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    yearId: z.uuid(),
    q: z.optional(z.union([z.string(), z.null()])),
  }),
});

/**
 * Response Get Students Api V1 Students  Get
 * Successful Response
 */
export const zGetStudentsResponse = z.array(zStudentBasicInfo);
