"""auth Session to be global

Revision ID: 24f56c549cb3
Revises: c348ed3ab192
Create Date: 2026-05-14 21:46:25.341612

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24f56c549cb3"
down_revision: Union[str, Sequence[str], None] = "c348ed3ab192"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TENANT_ID_EXPR = "NULLIF(current_setting('app.current_school_id', true), '')::uuid"


def _policy_name(table_name: str) -> str:
    return f"rls_{table_name}_tenant_isolation"


def _enable_tenant_rls(table_name: str) -> None:
    policy_name = _policy_name(table_name)
    policy_expr = f"school_id = {TENANT_ID_EXPR}"
    op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
    op.execute(f"DROP POLICY IF EXISTS {policy_name} ON {table_name}")
    op.execute(f"CREATE POLICY {policy_name} ON {table_name} FOR ALL USING ({policy_expr}) WITH CHECK ({policy_expr})")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_audit_auth_session_school"), "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_audit_logs_auth_session_id_auth_sessions"),
        "audit_logs",
        "auth_sessions",
        ["auth_session_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_auth_sessions_school_id"), table_name="auth_sessions")
    op.drop_constraint(op.f("uq_auth_session_id_school_id"), "auth_sessions", type_="unique")
    op.drop_constraint(op.f("fk_auth_sessions_school_id_schools"), "auth_sessions", type_="foreignkey")
    op.drop_constraint(op.f("fk_auth_session_membership_school"), "auth_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_auth_sessions_user_id_users"),
        "auth_sessions",
        "users",
        ["user_id"],
        ["id"],
    )

    op.execute("DROP POLICY IF EXISTS rls_auth_sessions_tenant_isolation ON auth_sessions")
    op.execute("ALTER TABLE auth_sessions NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE auth_sessions DISABLE ROW LEVEL SECURITY")

    op.drop_column("auth_sessions", "school_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "auth_sessions",
        sa.Column("school_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    _enable_tenant_rls("auth_sessions")
    op.drop_constraint(op.f("fk_auth_sessions_user_id_users"), "auth_sessions", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_auth_session_membership_school"),
        "auth_sessions",
        "school_memberships",
        ["user_id", "school_id"],
        ["user_id", "school_id"],
    )
    op.create_foreign_key(
        op.f("fk_auth_sessions_school_id_schools"),
        "auth_sessions",
        "schools",
        ["school_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("uq_auth_session_id_school_id"),
        "auth_sessions",
        ["id", "school_id"],
    )
    op.create_index(op.f("ix_auth_sessions_school_id"), "auth_sessions", ["school_id"], unique=False)
    op.drop_constraint(
        op.f("fk_audit_logs_auth_session_id_auth_sessions"),
        "audit_logs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_audit_auth_session_school"),
        "audit_logs",
        "auth_sessions",
        ["auth_session_id", "school_id"],
        ["id", "school_id"],
    )
    # ### end Alembic commands ###
