"""update_year_model

Revision ID: 27abb738f940
Revises: 24f56c549cb3
Create Date: 2026-06-19 15:11:58.498621

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27abb738f940"
down_revision: Union[str, Sequence[str], None] = "24f56c549cb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_academic_terms_year_id"), "academic_terms", ["year_id"], unique=False)
    op.create_unique_constraint("uq_academic_term_year_name", "academic_terms", ["year_id", "name"])
    op.drop_constraint(op.f("fk_academic_terms_year_id_years"), "academic_terms", type_="foreignkey")
    op.create_foreign_key(
        "fk_academic_terms_year_school",
        "academic_terms",
        "years",
        ["year_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("ix_events_year_id"), "events", ["year_id"], unique=False)
    op.drop_constraint(op.f("fk_events_year_id_years"), "events", type_="foreignkey")
    op.create_unique_constraint("uq_student_id_school_id", "students", ["id", "school_id"])
    op.create_foreign_key(
        "fk_event_year_school",
        "events",
        "years",
        ["year_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("uq_grade_year_grade", "grades", ["year_id", "grade"])
    op.drop_constraint(op.f("fk_grades_year_id_years"), "grades", type_="foreignkey")
    op.create_foreign_key(
        "fk_grade_year_school",
        "grades",
        "years",
        ["year_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("uq_primary_membership_per_user"),
        table_name="school_memberships",
        postgresql_where="(is_primary = true)",
    )
    op.create_index(op.f("ix_sections_grade_id"), "sections", ["grade_id"], unique=False)
    op.create_unique_constraint("uq_section_grade_section", "sections", ["grade_id", "section"])
    op.drop_constraint(op.f("fk_sections_grade_id_grades"), "sections", type_="foreignkey")
    op.create_foreign_key(
        "fk_section_grade_school",
        "sections",
        "grades",
        ["grade_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("ix_streams_grade_id"), "streams", ["grade_id"], unique=False)
    op.create_unique_constraint("uq_stream_id_school_id", "streams", ["id", "school_id"])
    op.drop_constraint(op.f("fk_streams_grade_id_grades"), "streams", type_="foreignkey")
    op.create_foreign_key(
        "fk_stream_grade_school",
        "streams",
        "grades",
        ["grade_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.add_column("student_year_links", sa.Column("school_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_student_year_links_school_id"),
        "student_year_links",
        ["school_id"],
        unique=False,
    )
    op.create_unique_constraint("uq_student_year_links", "student_year_links", ["student_id", "year_id"])
    op.drop_constraint(
        op.f("fk_student_year_links_student_id_students"),
        "student_year_links",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_student_year_links_year_id_years"),
        "student_year_links",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_student_year_links_year_school",
        "student_year_links",
        "years",
        ["year_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_student_year_links_school_id_schools"),
        "student_year_links",
        "schools",
        ["school_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_student_year_links_student_school",
        "student_year_links",
        "students",
        ["student_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.add_column("student_year_records", sa.Column("school_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_student_year_records_school_id"),
        "student_year_records",
        ["school_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_student_year_records_year_id_years"),
        "student_year_records",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_student_year_records_student_id_students"),
        "student_year_records",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_student_year_records_grade_id_grades"),
        "student_year_records",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_student_year_records_stream_id_streams"),
        "student_year_records",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_student_year_records_year_school",
        "student_year_records",
        "years",
        ["year_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_student_year_records_student_school",
        "student_year_records",
        "students",
        ["student_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_student_year_records_stream_school",
        "student_year_records",
        "streams",
        ["stream_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_student_year_records_grade_school",
        "student_year_records",
        "grades",
        ["grade_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_student_year_records_school_id_schools"),
        "student_year_records",
        "schools",
        ["school_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("uq_subject_year_code", "subjects", ["year_id", "code"])
    op.create_unique_constraint("uq_subject_year_name", "subjects", ["year_id", "name"])
    op.drop_constraint(op.f("fk_subjects_year_id_years"), "subjects", type_="foreignkey")
    op.create_foreign_key(
        "fk_subject_year_school",
        "subjects",
        "years",
        ["year_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.add_column("yearly_subjects", sa.Column("school_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_yearly_subjects_school_id"),
        "yearly_subjects",
        ["school_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_yearly_subjects_subject_id_subjects"),
        "yearly_subjects",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_yearly_subjects_stream_id_streams"),
        "yearly_subjects",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_yearly_subjects_grade_id_grades"),
        "yearly_subjects",
        type_="foreignkey",
    )
    op.drop_constraint(op.f("fk_yearly_subjects_year_id_years"), "yearly_subjects", type_="foreignkey")
    op.create_foreign_key(
        "fk_yearly_subjects_year_school",
        "yearly_subjects",
        "years",
        ["year_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_yearly_subjects_school_id_schools"),
        "yearly_subjects",
        "schools",
        ["school_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_yearly_subjects_grade_school",
        "yearly_subjects",
        "grades",
        ["grade_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_yearly_subjects_subject_school",
        "yearly_subjects",
        "subjects",
        ["subject_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_yearly_subjects_stream_school",
        "yearly_subjects",
        "streams",
        ["stream_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("uq_year_school_name", "years", ["school_id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_year_school_name", "years", type_="unique")
    op.drop_constraint("fk_yearly_subjects_stream_school", "yearly_subjects", type_="foreignkey")
    op.drop_constraint("fk_yearly_subjects_subject_school", "yearly_subjects", type_="foreignkey")
    op.drop_constraint("fk_yearly_subjects_grade_school", "yearly_subjects", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_yearly_subjects_school_id_schools"),
        "yearly_subjects",
        type_="foreignkey",
    )
    op.drop_constraint("fk_yearly_subjects_year_school", "yearly_subjects", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_yearly_subjects_year_id_years"),
        "yearly_subjects",
        "years",
        ["year_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_yearly_subjects_grade_id_grades"),
        "yearly_subjects",
        "grades",
        ["grade_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_yearly_subjects_stream_id_streams"),
        "yearly_subjects",
        "streams",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_yearly_subjects_subject_id_subjects"),
        "yearly_subjects",
        "subjects",
        ["subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_yearly_subjects_school_id"), table_name="yearly_subjects")
    op.drop_column("yearly_subjects", "school_id")
    op.drop_constraint("fk_subject_year_school", "subjects", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_subjects_year_id_years"),
        "subjects",
        "years",
        ["year_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_subject_year_name", "subjects", type_="unique")
    op.drop_constraint("uq_subject_year_code", "subjects", type_="unique")
    op.drop_constraint(
        op.f("fk_student_year_records_school_id_schools"),
        "student_year_records",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_student_year_records_grade_school",
        "student_year_records",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_student_year_records_stream_school",
        "student_year_records",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_student_year_records_student_school",
        "student_year_records",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_student_year_records_year_school",
        "student_year_records",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_student_year_records_stream_id_streams"),
        "student_year_records",
        "streams",
        ["stream_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_student_year_records_grade_id_grades"),
        "student_year_records",
        "grades",
        ["grade_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_student_year_records_student_id_students"),
        "student_year_records",
        "students",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_student_year_records_year_id_years"),
        "student_year_records",
        "years",
        ["year_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_student_year_records_school_id"), table_name="student_year_records")
    op.drop_column("student_year_records", "school_id")
    op.drop_constraint("fk_student_year_links_student_school", "student_year_links", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_student_year_links_school_id_schools"),
        "student_year_links",
        type_="foreignkey",
    )
    op.drop_constraint("fk_student_year_links_year_school", "student_year_links", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_student_year_links_year_id_years"),
        "student_year_links",
        "years",
        ["year_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_student_year_links_student_id_students"),
        "student_year_links",
        "students",
        ["student_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_student_year_links", "student_year_links", type_="unique")
    op.drop_index(op.f("ix_student_year_links_school_id"), table_name="student_year_links")
    op.drop_column("student_year_links", "school_id")
    op.drop_constraint("fk_stream_grade_school", "streams", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_streams_grade_id_grades"),
        "streams",
        "grades",
        ["grade_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_stream_id_school_id", "streams", type_="unique")
    op.drop_index(op.f("ix_streams_grade_id"), table_name="streams")
    op.drop_constraint("fk_section_grade_school", "sections", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_sections_grade_id_grades"),
        "sections",
        "grades",
        ["grade_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_section_grade_section", "sections", type_="unique")
    op.drop_index(op.f("ix_sections_grade_id"), table_name="sections")
    op.create_index(
        op.f("uq_primary_membership_per_user"),
        "school_memberships",
        ["user_id"],
        unique=True,
        postgresql_where="(is_primary = true)",
    )
    op.drop_constraint("fk_grade_year_school", "grades", type_="foreignkey")
    op.drop_constraint("uq_student_id_school_id", "students", type_="unique")
    op.create_foreign_key(
        op.f("fk_grades_year_id_years"),
        "grades",
        "years",
        ["year_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_grade_year_grade", "grades", type_="unique")
    op.drop_constraint("fk_event_year_school", "events", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_events_year_id_years"),
        "events",
        "years",
        ["year_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_events_year_id"), table_name="events")
    op.drop_constraint("fk_academic_terms_year_school", "academic_terms", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_academic_terms_year_id_years"),
        "academic_terms",
        "years",
        ["year_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_academic_term_year_name", "academic_terms", type_="unique")
    op.drop_index(op.f("ix_academic_terms_year_id"), table_name="academic_terms")
    # ### end Alembic commands ###
