"""added FK Constraint for AuditLog

Revision ID: 2cf9c8b09b0a
Revises: 27ddccd0d6d1
Create Date: 2026-05-13 23:39:13.336100

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cf9c8b09b0a"
down_revision: Union[str, Sequence[str], None] = "27ddccd0d6d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_auth_session_id_school_id", "auth_sessions", ["id", "school_id"])
    op.drop_constraint(
        op.f("fk_audit_logs_auth_session_id_auth_sessions"),
        "audit_logs",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_audit_auth_session_school",
        "audit_logs",
        "auth_sessions",
        ["auth_session_id", "school_id"],
        ["id", "school_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_auth_session_id_school_id", "auth_sessions", type_="unique")
    op.drop_constraint("fk_audit_auth_session_school", "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_audit_logs_auth_session_id_auth_sessions"),
        "audit_logs",
        "auth_sessions",
        ["auth_session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
