"""update position table

Revision ID: 32f161f9adb5
Revises: f2f5b1369fb1
Create Date: 2026-08-11 20:29:12.084477

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32f161f9adb5"
down_revision: Union[str, Sequence[str], None] = "f2f5b1369fb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("positions", "salary_grade")
    op.drop_column("positions", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("positions", sa.Column("category", sa.VARCHAR(length=14), autoincrement=False, nullable=False))
    op.add_column("positions", sa.Column("salary_grade", sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
