"""added check and foreign-key constraint

Revision ID: 3586606ea694
Revises: 4f4ac7051b0e
Create Date: 2026-05-11 18:07:41.253457

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3586606ea694"
down_revision: Union[str, Sequence[str], None] = "4f4ac7051b0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_admins_school_membership_id_school_memberships"),
        "admins",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_admins_membership_school",
        "admins",
        "school_memberships",
        ["user_id", "school_id"],
        ["user_id", "school_id"],
    )
    op.drop_column("admins", "school_membership_id")
    op.create_foreign_key(
        "fk_audit_membership_school",
        "audit_logs",
        "school_memberships",
        ["user_id", "school_id"],
        ["user_id", "school_id"],
    )
    op.create_foreign_key(
        "fk_auth_session_membership_school",
        "auth_sessions",
        "school_memberships",
        ["user_id", "school_id"],
        ["user_id", "school_id"],
    )
    op.drop_constraint(
        op.f("fk_employees_school_membership_id_school_memberships"),
        "employees",
        type_="foreignkey",
    )
    op.drop_column("employees", "school_membership_id")
    op.drop_constraint(
        op.f("fk_parents_school_membership_id_school_memberships"),
        "parents",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_parents_membership_school",
        "parents",
        "school_memberships",
        ["user_id", "school_id"],
        ["user_id", "school_id"],
    )
    op.drop_column("parents", "school_membership_id")
    op.drop_constraint(
        op.f("fk_students_school_membership_id_school_memberships"),
        "students",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_students_membership_school",
        "students",
        "school_memberships",
        ["user_id", "school_id"],
        ["user_id", "school_id"],
    )
    op.drop_column("students", "school_membership_id")
    op.add_column(
        "transfer_requests",
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "transfer_requests",
        "payload",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.create_foreign_key(
        "fk_transfer_request_requested_by",
        "transfer_requests",
        "school_memberships",
        ["requested_by_membership_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_transfer_request_requested_by", "transfer_requests", type_="foreignkey")
    op.alter_column(
        "transfer_requests",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.drop_column("transfer_requests", "reviewed_at")
    op.add_column(
        "students",
        sa.Column("school_membership_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fk_students_membership_school", "students", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_students_school_membership_id_school_memberships"),
        "students",
        "school_memberships",
        ["school_membership_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "parents",
        sa.Column("school_membership_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fk_parents_membership_school", "parents", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_parents_school_membership_id_school_memberships"),
        "parents",
        "school_memberships",
        ["school_membership_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "employees",
        sa.Column("school_membership_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_employees_school_membership_id_school_memberships"),
        "employees",
        "school_memberships",
        ["school_membership_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("fk_auth_session_membership_school", "auth_sessions", type_="foreignkey")
    op.drop_constraint("fk_audit_membership_school", "audit_logs", type_="foreignkey")
    op.add_column(
        "admins",
        sa.Column("school_membership_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("fk_admins_membership_school", "admins", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_admins_school_membership_id_school_memberships"),
        "admins",
        "school_memberships",
        ["school_membership_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
