"""remove department_id from employee

Revision ID: 3d4161e864a6
Revises: 7189fae758a4
Create Date: 2026-08-10 23:31:30.165628

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3d4161e864a6"
down_revision: Union[str, Sequence[str], None] = "7189fae758a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_employee_department_school"), "employees", type_="foreignkey")
    op.drop_column("employees", "department_id")
    op.add_column("positions", sa.Column("department_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_position_department_school",
        "positions",
        "departments",
        ["department_id", "school_id"],
        ["id", "school_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_position_department_school", "positions", type_="foreignkey")
    op.drop_column("positions", "department_id")
    op.add_column("employees", sa.Column("department_id", sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(
        op.f("fk_employee_department_school"),
        "employees",
        "departments",
        ["department_id", "school_id"],
        ["id", "school_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
