"""added permission_enum

Revision ID: 5668cfae5856
Revises: 7756e77bc908
Create Date: 2026-06-27 23:41:09.673722

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5668cfae5856"
down_revision: Union[str, Sequence[str], None] = "7756e77bc908"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_employee_year_links_school_id"), table_name="employee_year_links")
    op.drop_table("employee_year_links")
    op.alter_column(
        "permissions",
        "code",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.Enum(
            "SCHOOLS_READ",
            "SCHOOLS_MANAGE",
            "YEARS_READ",
            "YEARS_WRITE",
            "GRADES_READ",
            "GRADES_WRITE",
            "SUBJECTS_READ",
            "SUBJECTS_WRITE",
            "STREAMS_READ",
            "STREAMS_WRITE",
            "SECTIONS_READ",
            "SECTIONS_WRITE",
            "STUDENTS_READ",
            "STUDENTS_WRITE",
            "EMPLOYEES_READ",
            "EMPLOYEES_WRITE",
            "REGISTRATIONS_CREATE",
            "TEACHERS_ASSIGN",
            "AUTH_SWITCH_SCHOOL",
            "RECORDS_TRANSFER",
            name="permission_code_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "permissions",
        "code",
        existing_type=sa.Enum(
            "SCHOOLS_READ",
            "SCHOOLS_MANAGE",
            "YEARS_READ",
            "YEARS_WRITE",
            "GRADES_READ",
            "GRADES_WRITE",
            "SUBJECTS_READ",
            "SUBJECTS_WRITE",
            "STREAMS_READ",
            "STREAMS_WRITE",
            "SECTIONS_READ",
            "SECTIONS_WRITE",
            "STUDENTS_READ",
            "STUDENTS_WRITE",
            "EMPLOYEES_READ",
            "EMPLOYEES_WRITE",
            "REGISTRATIONS_CREATE",
            "TEACHERS_ASSIGN",
            "AUTH_SWITCH_SCHOOL",
            "RECORDS_TRANSFER",
            name="permission_code_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )
    op.create_table(
        "employee_year_links",
        sa.Column("employee_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("year_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("school_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["employee_id", "school_id"],
            ["employees.id", "employees.school_id"],
            name=op.f("fk_employee_year_links_employee_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_employee_year_links_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["year_id", "school_id"],
            ["years.id", "years.school_id"],
            name=op.f("fk_employee_year_links_year_school"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("employee_id", "year_id", name=op.f("pk_employee_year_links")),
        sa.UniqueConstraint(
            "employee_id",
            "year_id",
            name=op.f("uq_employee_year_links"),
            postgresql_include=[],
        ),
    )
    op.create_index(
        op.f("ix_employee_year_links_school_id"),
        "employee_year_links",
        ["school_id"],
        unique=False,
    )
    # ### end Alembic commands ###
