"""better user guardian relationships

Revision ID: 7189fae758a4
Revises: c118fad515b8
Create Date: 2026-08-10 23:13:29.647046

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7189fae758a4"
down_revision: Union[str, Sequence[str], None] = "c118fad515b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_guardians",
        sa.Column("guardian_user_id", sa.UUID(), nullable=False),
        sa.Column("dependent_user_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["dependent_user_id"],
            ["users.id"],
            name=op.f("fk_user_guardians_dependent_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["guardian_user_id"],
            ["users.id"],
            name=op.f("fk_user_guardians_guardian_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("guardian_user_id", "dependent_user_id", "id", name=op.f("pk_user_guardians")),
        sa.UniqueConstraint("guardian_user_id", "dependent_user_id", name="uq_user_guardians"),
    )
    op.drop_table("parent_student_links")
    op.drop_index(op.f("ix_parents_school_id"), table_name="parents")
    op.drop_table("parents")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parents",
        sa.Column("relation", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("emergency_contact_phone", sa.VARCHAR(length=25), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("school_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["school_id"], ["schools.id"], name=op.f("fk_parents_school_id_schools"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "school_id"],
            ["school_memberships.user_id", "school_memberships.school_id"],
            name=op.f("fk_parents_membership_school"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parents")),
    )
    op.create_index(op.f("ix_parents_school_id"), "parents", ["school_id"], unique=False)
    op.create_table(
        "parent_student_links",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("parent_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("student_user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_user_id"],
            ["users.id"],
            name=op.f("fk_parent_student_links_parent_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_user_id"],
            ["users.id"],
            name=op.f("fk_parent_student_links_student_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "parent_user_id",
            "student_user_id",
            name=op.f("uq_parent_student_links"),
            postgresql_include=[],
        ),
    )
    op.drop_table("user_guardians")
    # ### end Alembic commands ###
