"""add comments to columns

Revision ID: 7caed313a3ea
Revises: f02c1430e1ff
Create Date: 2026-06-23 13:33:23.472398

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7caed313a3ea"
down_revision: Union[str, Sequence[str], None] = "f02c1430e1ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student_term_records",
        "rank",
        existing_type=sa.INTEGER(),
        comment="Overall rank of the student in the class for this term.",
        existing_nullable=True,
    )
    op.alter_column(
        "student_year_records",
        "rank",
        existing_type=sa.INTEGER(),
        comment="Overall rank of the student in the class for this year.",
        existing_nullable=True,
    )
    op.alter_column(
        "subject_term_results",
        "rank",
        existing_type=sa.INTEGER(),
        comment="Rank of the student in this subject for this term.",
        existing_nullable=True,
    )
    op.alter_column(
        "subject_yearly_averages",
        "rank",
        existing_type=sa.INTEGER(),
        comment="Rank of the student in this subject for this year.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subject_yearly_averages",
        "rank",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Rank of the student in this subject for this year.",
        existing_nullable=True,
    )
    op.alter_column(
        "subject_term_results",
        "rank",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Rank of the student in this subject for this term.",
        existing_nullable=True,
    )
    op.alter_column(
        "student_year_records",
        "rank",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Overall rank of the student in the class for this year.",
        existing_nullable=True,
    )
    op.alter_column(
        "student_term_records",
        "rank",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Overall rank of the student in the class for this term.",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
