"""Assessment Models Refactoring

Revision ID: 856105b4872f
Revises: fa9545cac9f2
Create Date: 2026-06-21 16:06:29.902482

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "856105b4872f"
down_revision: Union[str, Sequence[str], None] = "fa9545cac9f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assessment_schemes",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_assessment_schemes_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_schemes")),
        sa.UniqueConstraint("id", "school_id", name="uq_assessment_scheme_id_school_id"),
        sa.UniqueConstraint("school_id", "name", name="uq_assessment_scheme_school_name"),
    )
    op.create_index(
        op.f("ix_assessment_schemes_school_id"),
        "assessment_schemes",
        ["school_id"],
        unique=False,
    )
    op.create_table(
        "assessment_scheme_components",
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column("assessment_scheme_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_scheme_id", "school_id"],
            ["assessment_schemes.id", "assessment_schemes.school_id"],
            name="fk_assessment_scheme_component_scheme_school",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_assessment_scheme_components_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_scheme_components")),
        sa.UniqueConstraint("id", "school_id", name="uq_assessment_scheme_component_id_school_id"),
        sa.UniqueConstraint(
            "school_id",
            "assessment_scheme_id",
            "name",
            name="uq_assessment_scheme_component_name",
        ),
    )
    op.create_index(
        op.f("ix_assessment_scheme_components_school_id"),
        "assessment_scheme_components",
        ["school_id"],
        unique=False,
    )
    op.add_column(
        "assessment_scores",
        sa.Column("assessment_scheme_component_id", sa.UUID(), nullable=False),
    )
    op.drop_constraint(
        op.f("uq_assessment_score_result_component"),
        "assessment_scores",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_assessment_score_result_component",
        "assessment_scores",
        ["school_id", "subject_term_result_id", "assessment_scheme_component_id"],
    )
    op.drop_constraint(
        op.f("fk_assessment_score_component_school"),
        "assessment_scores",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_assessment_score_component_school",
        "assessment_scores",
        "assessment_scheme_components",
        ["assessment_scheme_component_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.drop_column("assessment_scores", "assessment_component_id")
    op.add_column(
        "subject_offerings",
        sa.Column("assessment_scheme_id", sa.UUID(), nullable=False),
    )
    op.create_foreign_key(
        "fk_subject_offerings_assessment_scheme_school",
        "subject_offerings",
        "assessment_schemes",
        ["assessment_scheme_id", "school_id"],
        ["id", "school_id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_assessment_scheme_component_term_school",
        "assessment_scheme_components",
        "academic_terms",
        ["term_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_assessment_components_school_id"), table_name="assessment_components")
    op.drop_table("assessment_components")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_subject_offerings_assessment_scheme_school",
        "subject_offerings",
        type_="foreignkey",
    )
    op.drop_column("subject_offerings", "assessment_scheme_id")
    op.add_column(
        "assessment_scores",
        sa.Column("assessment_component_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_assessment_score_component_school", "assessment_scores", type_="foreignkey")
    op.create_table(
        "assessment_components",
        sa.Column("term_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subject_offering_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "weight",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "max_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("display_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("school_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_assessment_components_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_offering_id", "school_id"],
            ["subject_offerings.id", "subject_offerings.school_id"],
            name=op.f("fk_assessment_component_subject_offering_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id", "school_id"],
            ["academic_terms.id", "academic_terms.school_id"],
            name=op.f("fk_assessment_component_term_school"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessment_components")),
        sa.UniqueConstraint(
            "id",
            "school_id",
            name=op.f("uq_assessment_component_id_school_id"),
            postgresql_include=[],
        ),
        sa.UniqueConstraint(
            "school_id",
            "term_id",
            "subject_offering_id",
            "name",
            name=op.f("uq_assessment_component_scheme_name"),
            postgresql_include=[],
        ),
    )
    op.create_index(
        op.f("ix_assessment_components_school_id"),
        "assessment_components",
        ["school_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_assessment_score_component_school"),
        "assessment_scores",
        "assessment_components",
        ["assessment_component_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_assessment_score_result_component", "assessment_scores", type_="unique")
    op.create_unique_constraint(
        op.f("uq_assessment_score_result_component"),
        "assessment_scores",
        ["school_id", "subject_term_result_id", "assessment_component_id"],
    )
    op.drop_constraint(
        "fk_assessment_scheme_component_term_school",
        "assessment_scheme_components",
        type_="foreignkey",
    )
    op.drop_column("assessment_scores", "assessment_scheme_component_id")
    op.drop_index(
        op.f("ix_assessment_scheme_components_school_id"),
        table_name="assessment_scheme_components",
    )
    op.drop_table("assessment_scheme_components")
    op.drop_index(op.f("ix_assessment_schemes_school_id"), table_name="assessment_schemes")
    op.drop_table("assessment_schemes")
    # ### end Alembic commands ###
