"""refactor subject offering

Revision ID: 8eccbd090f8d
Revises: e8089484a5b5
Create Date: 2026-06-20 16:36:46.776482

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8eccbd090f8d"
down_revision: Union[str, Sequence[str], None] = "e8089484a5b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subject_offerings",
        sa.Column("year_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("grade_id", sa.UUID(), nullable=False),
        sa.Column("stream_id", sa.UUID(), nullable=True),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grade_id", "school_id"],
            ["grades.id", "grades.school_id"],
            name="fk_subject_offerings_grade_school",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_subject_offerings_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stream_id", "school_id"],
            ["streams.id", "streams.school_id"],
            name="fk_subject_offerings_stream_school",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "school_id"],
            ["subjects.id", "subjects.school_id"],
            name="fk_subject_offerings_subject_definition_school",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["year_id", "school_id"],
            ["years.id", "years.school_id"],
            name="fk_subject_offerings_year_school",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subject_offerings")),
        sa.UniqueConstraint("id", "school_id", name="uq_subject_offering_id_school_id"),
        sa.UniqueConstraint(
            "school_id",
            "year_id",
            "grade_id",
            "stream_id",
            "subject_id",
            name="uq_subject_offering_offering_scope",
        ),
    )
    op.create_index(
        op.f("ix_subject_offerings_school_id"),
        "subject_offerings",
        ["school_id"],
        unique=False,
    )
    op.add_column(
        "assessments",
        sa.Column("subject_offering_id", sa.UUID(), nullable=False),
    )
    op.add_column(
        "subject_yearly_averages",
        sa.Column("subject_offering_id", sa.UUID(), nullable=False),
    )
    op.add_column(
        "teaching_assignments",
        sa.Column("subject_offering_id", sa.UUID(), nullable=False),
    )

    op.drop_constraint(
        op.f("fk_assessments_yearly_subject_id_yearly_subjects"),
        "assessments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_subject_yearly_averages_yearly_subject_id_yearly_subjects"),
        "subject_yearly_averages",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_teaching_assignment_yearly_subject_school"),
        "teaching_assignments",
        type_="foreignkey",
    )

    op.create_foreign_key(
        op.f("fk_assessments_subject_offering_id_subject_offerings"),
        "assessments",
        "subject_offerings",
        ["subject_offering_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_subject_yearly_averages_subject_offering_id_subject_offerings"),
        "subject_yearly_averages",
        "subject_offerings",
        ["subject_offering_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_teaching_assignment_subject_offering_school",
        "teaching_assignments",
        "subject_offerings",
        ["subject_offering_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )

    op.drop_constraint(
        op.f("uq_teaching_assignment_scope"),
        "teaching_assignments",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_teaching_assignment_scope",
        "teaching_assignments",
        ["school_id", "teacher_profile_id", "subject_offering_id", "class_section_id"],
    )

    op.drop_column("assessments", "yearly_subject_id")
    op.drop_column("teaching_assignments", "yearly_subject_id")
    op.drop_column("subject_yearly_averages", "yearly_subject_id")

    op.drop_table("grade_stream_subjects")
    op.drop_index(op.f("ix_yearly_subjects_school_id"), table_name="yearly_subjects")
    op.drop_table("yearly_subjects")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "yearly_subjects",
        sa.Column("subject_code", sa.VARCHAR(length=25), autoincrement=False, nullable=False),
        sa.Column("year_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subject_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("grade_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("stream_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("school_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["grade_id", "school_id"],
            ["grades.id", "grades.school_id"],
            name=op.f("fk_yearly_subjects_grade_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_yearly_subjects_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stream_id", "school_id"],
            ["streams.id", "streams.school_id"],
            name=op.f("fk_yearly_subjects_stream_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "school_id"],
            ["subjects.id", "subjects.school_id"],
            name=op.f("fk_yearly_subjects_subject_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["year_id", "school_id"],
            ["years.id", "years.school_id"],
            name=op.f("fk_yearly_subjects_year_school"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_yearly_subjects")),
        sa.UniqueConstraint(
            "id",
            "school_id",
            name=op.f("uq_yearly_subject_id_school_id"),
            postgresql_include=[],
        ),
        sa.UniqueConstraint(
            "school_id",
            "year_id",
            "grade_id",
            "stream_id",
            "subject_id",
            name=op.f("uq_yearly_subject_offering_scope"),
            postgresql_include=[],
        ),
    )
    op.create_table(
        "grade_stream_subjects",
        sa.Column("grade_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("stream_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("subject_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"],
            ["grades.id"],
            name=op.f("fk_grade_stream_subjects_grade_id_grades"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stream_id"],
            ["streams.id"],
            name=op.f("fk_grade_stream_subjects_stream_id_streams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_grade_stream_subjects_subject_id_subjects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grade_stream_subjects")),
        sa.UniqueConstraint(
            "grade_id",
            "stream_id",
            "subject_id",
            name=op.f("uq_grade_stream_subject"),
            postgresql_include=[],
        ),
    )
    op.drop_constraint(
        op.f("fk_assessments_subject_offering_id_subject_offerings"),
        "assessments",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_subject_yearly_averages_subject_offering_id_subject_offerings"),
        "subject_yearly_averages",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_teaching_assignment_subject_offering_school",
        "teaching_assignments",
        type_="foreignkey",
    )

    op.create_index(
        op.f("ix_yearly_subjects_school_id"),
        "yearly_subjects",
        ["school_id"],
        unique=False,
    )

    op.add_column(
        "teaching_assignments",
        sa.Column("yearly_subject_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "subject_yearly_averages",
        sa.Column("yearly_subject_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "assessments",
        sa.Column("yearly_subject_id", sa.UUID(), autoincrement=False, nullable=False),
    )

    op.create_foreign_key(
        op.f("fk_teaching_assignment_yearly_subject_school"),
        "teaching_assignments",
        "yearly_subjects",
        ["yearly_subject_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_subject_yearly_averages_yearly_subject_id_yearly_subjects"),
        "subject_yearly_averages",
        "yearly_subjects",
        ["yearly_subject_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_assessments_yearly_subject_id_yearly_subjects"),
        "assessments",
        "yearly_subjects",
        ["yearly_subject_id"],
        ["id"],
        ondelete="CASCADE",
    )

    op.drop_constraint("uq_teaching_assignment_scope", "teaching_assignments", type_="unique")
    op.create_unique_constraint(
        op.f("uq_teaching_assignment_scope"),
        "teaching_assignments",
        ["school_id", "teacher_profile_id", "yearly_subject_id", "class_section_id"],
    )

    op.drop_column("teaching_assignments", "subject_offering_id")
    op.drop_column("subject_yearly_averages", "subject_offering_id")
    op.drop_column("assessments", "subject_offering_id")
    op.drop_index(op.f("ix_subject_offerings_school_id"), table_name="subject_offerings")
    op.drop_table("subject_offerings")
    # ### end Alembic commands ###
