"""make grade table global

Revision ID: a4a8dea03736
Revises: b02b2388784c
Create Date: 2026-06-20 11:31:46.512238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4a8dea03736"
down_revision: Union[str, Sequence[str], None] = "b02b2388784c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_employee_year_links", "employee_year_links", ["employee_id", "year_id"])
    op.drop_index(op.f("ix_grades_year_id"), table_name="grades")
    op.drop_constraint(op.f("uq_grade_year_grade"), "grades", type_="unique")
    op.drop_constraint(op.f("fk_grade_year_school"), "grades", type_="foreignkey")
    op.drop_column("grades", "year_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_teaching_assignment_scope", "teaching_assignments", type_="unique")
    op.add_column("grades", sa.Column("year_id", sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(
        op.f("fk_grade_year_school"),
        "grades",
        "years",
        ["year_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint(
        op.f("uq_grade_year_grade"),
        "grades",
        ["year_id", "grade"],
    )
    op.create_index(op.f("ix_grades_year_id"), "grades", ["year_id"], unique=False)
    op.drop_constraint("uq_employee_year_links", "employee_year_links", type_="unique")
    # ### end Alembic commands ###
