"""update Payroll Profile

Revision ID: b3a97b08e1cb
Revises: 903f365ac583
Create Date: 2026-07-06 21:36:26.193583

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3a97b08e1cb"
down_revision: Union[str, Sequence[str], None] = "903f365ac583"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payroll_profiles", sa.Column("bank_name", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payroll_profiles", "bank_name")
    # ### end Alembic commands ###
