"""drop mark_list

Revision ID: b5603fcc66bc
Revises: 76a074410a21
Create Date: 2026-06-21 13:51:12.422333

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5603fcc66bc"
down_revision: Union[str, Sequence[str], None] = "76a074410a21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mark_lists")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mark_lists",
        sa.Column("student_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("student_term_record_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subject_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(length=10), autoincrement=False, nullable=False),
        sa.Column("percentage", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_mark_lists_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_term_record_id"],
            ["student_term_records.id"],
            name=op.f("fk_mark_lists_student_term_record_id_student_term_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_mark_lists_subject_id_subjects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mark_lists")),
    )
    # ### end Alembic commands ###
