"""user employment and enrollment

Revision ID: c118fad515b8
Revises: f4575ff3ae8e
Create Date: 2026-08-08 21:25:54.183554

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c118fad515b8"
down_revision: Union[str, Sequence[str], None] = "f4575ff3ae8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employment_positions",
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "academic",
                "administration",
                "finance",
                "hr",
                "it",
                "operations",
                "support",
                "other",
                name="position_category_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "contract",
                "temporary",
                "substitute",
                "internship",
                name="employment_position_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "open", "closed", "archived", name="employment_position_status_enum", native_enum=False),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("requirements", sa.JSON(), nullable=False),
        sa.Column("responsibilities", sa.JSON(), nullable=False),
        sa.Column("benefits", sa.JSON(), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=True),
        sa.Column("application_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("openings_count", sa.Integer(), nullable=False),
        sa.Column("allow_applications", sa.Boolean(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"], ["schools.id"], name=op.f("fk_employment_positions_school_id_schools"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employment_positions")),
        sa.UniqueConstraint("id", "school_id", name="uq_employment_position_id_school_id"),
        sa.UniqueConstraint("school_id", "title", name="uq_employment_position_school_title"),
    )
    op.create_index(op.f("ix_employment_positions_school_id"), "employment_positions", ["school_id"], unique=False)
    op.create_table(
        "employment_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("city", sa.String(length=80), nullable=False),
        sa.Column("highest_education", sa.String(length=120), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("field_of_study", sa.String(length=120), nullable=True),
        sa.Column("institution", sa.String(length=160), nullable=True),
        sa.Column("years_of_experience", sa.Integer(), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("certifications", sa.JSON(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_employment_profiles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employment_profiles")),
        sa.UniqueConstraint("user_id", name="uq_employment_profile_user"),
    )
    op.create_index(op.f("ix_employment_profiles_user_id"), "employment_profiles", ["user_id"], unique=False)
    op.create_table(
        "employment_applications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "under_review",
                "shortlisted",
                "accepted",
                "rejected",
                "withdrawn",
                name="employment_application_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("profile_snapshot", sa.JSON(), nullable=False),
        sa.Column("applicant_note", sa.Text(), nullable=True),
        sa.Column("reviewer_note", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["employment_positions.id"],
            name=op.f("fk_employment_applications_position_id_employment_positions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["employment_profiles.id"],
            name=op.f("fk_employment_applications_profile_id_employment_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["schools.id"], name=op.f("fk_employment_applications_school_id_schools"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_employment_applications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employment_applications")),
        sa.UniqueConstraint("id", "school_id", name="uq_employment_application_id_school_id"),
        sa.UniqueConstraint("user_id", "position_id", name="uq_employment_application_user_position"),
    )
    op.create_index(
        op.f("ix_employment_applications_position_id"), "employment_applications", ["position_id"], unique=False
    )
    op.create_index(
        op.f("ix_employment_applications_profile_id"), "employment_applications", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_employment_applications_school_id"), "employment_applications", ["school_id"], unique=False
    )
    op.create_index(op.f("ix_employment_applications_user_id"), "employment_applications", ["user_id"], unique=False)
    op.create_table(
        "enrollment_opportunities",
        sa.Column("academic_year_id", sa.UUID(), nullable=False),
        sa.Column("grade_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "open", "closed", "archived", name="enrollment_opportunity_status_enum", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("application_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("allow_applications", sa.Boolean(), nullable=False),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["academic_year_id"],
            ["years.id"],
            name=op.f("fk_enrollment_opportunities_academic_year_id_years"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["grades.id"], name=op.f("fk_enrollment_opportunities_grade_id_grades"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["schools.id"],
            name=op.f("fk_enrollment_opportunities_school_id_schools"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollment_opportunities")),
        sa.UniqueConstraint("id", "school_id", name="uq_enrollment_opportunity_id_school_id"),
        sa.UniqueConstraint(
            "school_id", "academic_year_id", "grade_id", name="uq_enrollment_opportunity_school_year_grade"
        ),
    )
    op.create_index(
        op.f("ix_enrollment_opportunities_academic_year_id"),
        "enrollment_opportunities",
        ["academic_year_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_enrollment_opportunities_grade_id"), "enrollment_opportunities", ["grade_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollment_opportunities_school_id"), "enrollment_opportunities", ["school_id"], unique=False
    )
    op.create_table(
        "enrollment_applications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "under_review",
                "accepted",
                "rejected",
                "withdrawn",
                name="enrollment_application_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("student_info", sa.JSON(), nullable=False),
        sa.Column("applicant_note", sa.Text(), nullable=True),
        sa.Column("reviewer_note", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("school_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["enrollment_opportunities.id"],
            name=op.f("fk_enrollment_applications_opportunity_id_enrollment_opportunities"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"], ["schools.id"], name=op.f("fk_enrollment_applications_school_id_schools"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_enrollment_applications_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_enrollment_applications")),
        sa.UniqueConstraint("id", "school_id", name="uq_enrollment_application_id_school_id"),
    )
    op.create_index(
        op.f("ix_enrollment_applications_opportunity_id"), "enrollment_applications", ["opportunity_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollment_applications_school_id"), "enrollment_applications", ["school_id"], unique=False
    )
    op.create_index(op.f("ix_enrollment_applications_user_id"), "enrollment_applications", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enrollment_applications_user_id"), table_name="enrollment_applications")
    op.drop_index(op.f("ix_enrollment_applications_school_id"), table_name="enrollment_applications")
    op.drop_index(op.f("ix_enrollment_applications_opportunity_id"), table_name="enrollment_applications")
    op.drop_table("enrollment_applications")
    op.drop_index(op.f("ix_enrollment_opportunities_school_id"), table_name="enrollment_opportunities")
    op.drop_index(op.f("ix_enrollment_opportunities_grade_id"), table_name="enrollment_opportunities")
    op.drop_index(op.f("ix_enrollment_opportunities_academic_year_id"), table_name="enrollment_opportunities")
    op.drop_table("enrollment_opportunities")
    op.drop_index(op.f("ix_employment_applications_user_id"), table_name="employment_applications")
    op.drop_index(op.f("ix_employment_applications_school_id"), table_name="employment_applications")
    op.drop_index(op.f("ix_employment_applications_profile_id"), table_name="employment_applications")
    op.drop_index(op.f("ix_employment_applications_position_id"), table_name="employment_applications")
    op.drop_table("employment_applications")
    op.drop_index(op.f("ix_employment_profiles_user_id"), table_name="employment_profiles")
    op.drop_table("employment_profiles")
    op.drop_index(op.f("ix_employment_positions_school_id"), table_name="employment_positions")
    op.drop_table("employment_positions")
    # ### end Alembic commands ###
