"""Role names use Enums

Revision ID: c348ed3ab192
Revises: f83922454143
Create Date: 2026-05-14 18:23:23.879337

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c348ed3ab192"
down_revision: Union[str, Sequence[str], None] = "f83922454143"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles",
        "name",
        existing_type=sa.VARCHAR(length=80),
        type_=sa.Enum(
            "owner",
            "admin",
            "teacher",
            "student",
            "registrar",
            "parent",
            "employee",
            name="roll_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "roles",
        "name",
        existing_type=sa.Enum(
            "owner",
            "admin",
            "teacher",
            "student",
            "registrar",
            "parent",
            "employee",
            name="roll_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=80),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
