"""trigger that validates the year_id of the student_year_record
matches the year_id of the subject_offering before the insert is allowed.

Revision ID: de20a8e4ad51
Revises: 856105b4872f
Create Date: 2026-06-21 16:44:08.100668

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de20a8e4ad51"
down_revision: Union[str, Sequence[str], None] = "856105b4872f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_subject_yearly_average_record_subject_pair",
        "subject_yearly_averages",
        ["student_year_record_id", "subject_offering_id"],
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION validate_subject_yearly_average_year_match()
        RETURNS trigger AS $$
        DECLARE
            student_year_id uuid;
            offering_year_id uuid;
        BEGIN
            SELECT se.year_id
            INTO student_year_id
            FROM student_year_records syr
            JOIN student_enrollments se
                ON se.id = syr.student_enrollment_id
               AND se.school_id = syr.school_id
            WHERE syr.id = NEW.student_year_record_id
              AND syr.school_id = NEW.school_id;

            SELECT so.year_id
            INTO offering_year_id
            FROM subject_offerings so
            WHERE so.id = NEW.subject_offering_id
              AND so.school_id = NEW.school_id;

            IF student_year_id IS DISTINCT FROM offering_year_id THEN
                RAISE EXCEPTION 'subject_yearly_average year mismatch';
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )

    op.execute(
        """
        CREATE TRIGGER trg_validate_subject_yearly_average_year_match
        BEFORE INSERT OR UPDATE ON subject_yearly_averages
        FOR EACH ROW
        EXECUTE FUNCTION validate_subject_yearly_average_year_match();
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_subject_yearly_average_record_subject_pair",
        "subject_yearly_averages",
        type_="unique",
    )

    op.execute(
        """
        DROP TRIGGER IF EXISTS trg_validate_subject_yearly_average_year_match
        ON subject_yearly_averages;
        """
    )

    op.execute(
        """
        DROP FUNCTION IF EXISTS validate_subject_yearly_average_year_match();
        """
    )

    # ### end Alembic commands ###
