"""rename constraint

Revision ID: f2f5b1369fb1
Revises: 9e344fb3f531
Create Date: 2026-08-11 19:18:11.172976

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2f5b1369fb1"
down_revision: Union[str, Sequence[str], None] = "9e344fb3f531"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_assessment_scheme_component_name"), "assessment_scheme_components", type_="unique")
    op.create_unique_constraint(
        "uq_assessment_scheme_component_school_scheme_term_name",
        "assessment_scheme_components",
        ["school_id", "assessment_scheme_id", "term_id", "name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_assessment_scheme_component_school_scheme_term_name", "assessment_scheme_components", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_assessment_scheme_component_name"),
        "assessment_scheme_components",
        ["school_id", "assessment_scheme_id", "name"],
    )
    # ### end Alembic commands ###
