"""Roles are shared across all schools

Revision ID: f83922454143
Revises: ab31ea8954f5
Create Date: 2026-05-14 15:29:40.421900

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f83922454143"
down_revision: Union[str, Sequence[str], None] = "ab31ea8954f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

TENANT_ID_EXPR = "NULLIF(current_setting('app.current_school_id', true), '')::uuid"


def _policy_name(table_name: str) -> str:
    return f"rls_{table_name}_tenant_isolation"


def _enable_tenant_rls(table_name: str) -> None:
    policy_name = _policy_name(table_name)
    policy_expr = f"school_id = {TENANT_ID_EXPR}"
    op.execute(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY")
    op.execute(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY")
    op.execute(f"DROP POLICY IF EXISTS {policy_name} ON {table_name}")
    op.execute(f"CREATE POLICY {policy_name} ON {table_name} FOR ALL USING ({policy_expr}) WITH CHECK ({policy_expr})")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_membership_role_role_school"), "membership_roles", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_membership_roles_role_id_roles"),
        "membership_roles",
        "roles",
        ["role_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_roles_school_id"), table_name="roles")
    op.drop_constraint(op.f("uq_role_id_school_id"), "roles", type_="unique")
    op.drop_constraint(op.f("uq_role_school_name"), "roles", type_="unique")
    op.create_unique_constraint("uq_role_name", "roles", ["name"])
    op.drop_constraint(op.f("fk_roles_school_id_schools"), "roles", type_="foreignkey")

    op.execute("DROP POLICY IF EXISTS rls_roles_tenant_isolation ON roles")
    op.execute("ALTER TABLE roles NO FORCE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE roles DISABLE ROW LEVEL SECURITY")

    op.drop_column("roles", "school_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("roles", sa.Column("school_id", sa.UUID(), autoincrement=False, nullable=False))
    _enable_tenant_rls("roles")

    op.create_foreign_key(
        op.f("fk_roles_school_id_schools"),
        "roles",
        "schools",
        ["school_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("uq_role_name", "roles", type_="unique")
    op.create_unique_constraint(
        op.f("uq_role_school_name"),
        "roles",
        ["school_id", "name"],
    )
    op.create_unique_constraint(
        op.f("uq_role_id_school_id"),
        "roles",
        ["id", "school_id"],
    )
    op.create_index(op.f("ix_roles_school_id"), "roles", ["school_id"], unique=False)
    op.drop_constraint(
        op.f("fk_membership_roles_role_id_roles"),
        "membership_roles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_membership_role_role_school"),
        "membership_roles",
        "roles",
        ["role_id", "school_id"],
        ["id", "school_id"],
    )
    # ### end Alembic commands ###
