"""added teaching_assignment_id

Revision ID: fa9545cac9f2
Revises: b5603fcc66bc
Create Date: 2026-06-21 14:32:50.743006

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa9545cac9f2"
down_revision: Union[str, Sequence[str], None] = "b5603fcc66bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subject_term_results",
        sa.Column("teaching_assignment_id", sa.UUID(), nullable=False),
    )
    op.create_foreign_key(
        "fk_subject_term_result_teaching_assignment_school",
        "subject_term_results",
        "teaching_assignments",
        ["teaching_assignment_id", "school_id"],
        ["id", "school_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_subject_term_result_teaching_assignment_school",
        "subject_term_results",
        type_="foreignkey",
    )
    op.drop_column("subject_term_results", "teaching_assignment_id")
    # ### end Alembic commands ###
